pkg/platform/mgo/rdb.go
pkg/service/run/run.go
pkg/service/run/service.go

Also move the default checking code to service controller
fixes #9

fix: fix default number of testruns from 2 to 25.

---

.github/workflows/docker-publish.yml

To speed up onboarding we should publish prebuilt docker images. I'm adding a docker image that automatically builds and publishes Docker images on tag releases.

ci(docker): add github action for publishing docker images

---

docker-compose.yaml

building images for regular users can be time consuming and also requires atleast 12GB+ memory to build. Prebuilt docker images makes the experience faster and more approachable.

build(docker-compose): use prebuilt docker images for keploy

---

.github/workflows/go.yml

replaced `pull_request` with `pull_request_target` to ensure that github actions secret can be accessed for PRs. This is important to run keploy for testing during CI.

build(ci): enable secret actions for fork PRs

---

README.md

- Fixes #57 
- Added docker pull command to get the latest keploy image

docs(readme): add command to get the latest keploy image

---

.cz.toml
.github/workflows/release.yml
.pre-commit-config.yaml
.releaserc.json

Although we are using conventional commits, there are situations when the commit messages can have unwanted spaces. These spaces can be problematic for automatic releaser like `semantic releaser` - which is also added in this commit.

ci: add commit linting and automatic release

---

.github/workflows/go.yml
.github/workflows/release.yml

the `codfish/semantic-release-action` was failing because the `semantic-release/exec` wasn't
installed. So we are fixing this by adding the `additional_packages` in the actions to install it.

ci: fix failure in the automatic releaser

---

README.md

This adds Gitpod sample app URL to the README to speed up user onboarding.

docs(readme) : add gitpod option to readme

---

README.md
pkg/service/regression/regression.go

Closes: #107
Closes: #106
This commit adds safe escaping for logged user input in the `service/regression` package, replacing newlines with spaces and escaping HTML.
Logging, security.
None, but I could work on it if we need any.
N/A
None.

fix(logging): Escape logged user input for security

---

.github/workflows/docker-publish.yml
Dockerfile

Closes: #118
After some investigation, @slayerjain and I concluded that QEMU is not required by our multiarch build. This PR removes the setup-qemu step from the docker-publish workflow.
None.
NA
N/A

ci(publish-docker): Remove QEMU setup

---

.github/workflows/release.yml

There seems to be a problem with semantic releaser. I've disabled it until we solve it. 
I've also created an issue on the GitHub action that we are using - https://github.com/codfish/semantic-release-action/issues/168#issuecomment-1102815369

ci: disable semantic releaser temporarily

---

README.md

Update the documentation to have the ts/js and java sdk.

docs(readme): add reference for java and ts sdk

---

pkg/platform/telemetry/telemetry.go

(https://github.com/keploy/keploy/issues/150)
Closes: https://github.com/keploy/keploy/issues/150
Changed log level to Error from Fatal so that keploy doesn't exit in case of no internet
- [x ] Bug fix (non-breaking change which fixes an issue)
NA

change log level to error instead of fatal

---

pkg/platform/telemetry/telemetry.go
server/server.go

Signed-off-by: re-Tick <jain.ritik.1001@gmail.com>
- After disabling telemetry in keploy, unwanted telemetry ping call was occurring.
- Add a return statement when telemetry is disabled in the ping method of telemetry package.
- Set the logger level to info so that debug logs are avoided in console.
- But setting ENABLE_DEBUG env variable to true changes the logger level to "debug".

fix: skips the unusual tele call on disabling telemetry

---

grpc/grpcserver/server.go
pkg/service/mock/mock.go
server/server.go

Signed-off-by: re-Tick <jain.ritik.1001@gmail.com>
- keploy should generate a random name for mocks with no name tag.
- Uses uuid to generate name for mocks and write them to yaml file at the provided path directory.
- logs the auto generated mock name along with changes for unit tests configuration with keploy.

feat: generate mock name if empty and logs yaml file path

---

grpc/grpcserver/server.go
grpc/mock/mock.go
http/regression/regression.go
pkg/models/mock.go
pkg/service/regression/regression.go

the header's field-values are delimited to string seperated by comma
Signed-off-by: re-Tick <jain.ritik.1001@gmail.com>
- The yaml file's headers field-value should be comma seperated string instead of a string array.
Create a new request and response field type of http-spec to update the header type to map[string]string.

fix: updates the http-spec for comma delimiter

---

grpc/mock/mock.go

- Closes: #184
Compressed the data on Encode wiriting mocks into yaml and decompressed on Decode

feat: mock data compress-decompress

---

README.md

The latest version of keploy no longer needs mongo to be running for saving test results/runs or test cases.

docs(readme): remove mongo from readme

---

cmd/server/main.go
server/const.go
server/server.go

Keploy server did not use a global default version for starting the server. This PR adds a variable to the server file so that whenever the user does not pass a version to start the server, the server can start using the default version.
NA

Add default version to server

---

grpc/mock/mock.go

Signed-off-by: gouravkrosx <gouravgreatkr@gmail.com>
- Date type headers will be a single element

fix(grpc): comma separated date headers should be a single element

---

pkg/platform/fs/mock.go

- If a test doesn't have mocks then the keploy server gets crashes, for eg: 500 and 404 error codes.
Signed-off-by: gouravkrosx <gouravgreatkr@gmail.com>
- I have added a check for array length, if it's greater than 0 then do anything.
`NA`

fix: add length check condition for mocks array

---

pkg/hooks/connection/tracker.go
pkg/hooks/loader.go
pkg/proxy/proxy.go

Closes:  #632 
- Added a timeout of 2 seconds, after this duration we assume that all the data events would have come.
- Also fixed format of ipv6 address in proxy server. for eg: replace `::1:some_dest_port `->` [::1]:some_dest_port` 
`NA`

fix:add timeout when Connection:keep-alive is enabled in request 

---

pkg/proxy/proxy.go

- Keploy fails to record mocks for mongo db. 
- Instead of using customConn, used the same conn object in case of tls connection.
`NA`
- [x ] My code follows the style guidelines of this project.

fix: fails to create mongo db mocks

---

pkg/hooks/connection/factory.go
pkg/hooks/loader.go
pkg/service/test/test.go
pkg/util.go

- Removing resp channel from test and record flow.
Solves: #672
Removed resp channel from hooks and set the response for call in simulatehttp.
Ran the updated code with new as well as pre-existing samples to insure smooth functioning, along with projects that were breaking earlier due to this bug

[fix]:removing resp channel

---

.github/workflows/go-self-hosted.yml
.github/workflows/go.yml
.github/workflows/main-self-hosted.yml
.github/workflows/main.yml
.github/workflows/release.yml
Dockerfile
goreleaser.yaml

This makes the CI computable with Keploy V2. Keploy V2 binary is no longer compatible with windows and macOS. Instead keploy would run via docker on windows and macOS.

ci: update dockefile and gha for keploy v2

---

pkg/hooks/launch.go
pkg/proxy/util/util.go
pkg/util.go

- #689 
- Now, docker event listener will only listen for contianer-create events and handle that only for given application container name
- Disabled follow redirects for APIs with redirections to maintain response consistency.
Current Limitation: The docker compose file of user should be in the directory/subdirectory where keploy binary is running.
`NA`

fix: unable to use docker compose file to record/test via keploy

---

Dockerfile
cmd/examples.go
cmd/record.go
cmd/root.go
cmd/test.go

- Enhancing user experience by adding sample cases and updating logs
Closes: #694
Guiding when user enters wrong command, showing sample, adding support for debug mode.
| **<img width="1362" alt="image" src="https://github.com/keploy/keploy/assets/60891544/6f4852f1-c7f9-4de9-a2cd-5904f1739fd0">** | <img width="1372" alt="image" src="https://github.com/keploy/keploy/assets/60891544/8a912e6c-52bd-4321-a33b-9f386f7834f2"> |
| **<img width="1376" alt="image" src="https://github.com/keploy/keploy/assets/60891544/314384da-4e83-4f0c-8dbe-b9190c5f1543">** | <img width="1292" alt="image" src="https://github.com/keploy/keploy/assets/60891544/152e2c9d-f673-4601-830c-e038cd337f06"> |
| …

feat: revamp cli user experience and add examples

---

README.md

After #688, we no longer need to provide the `network` to keploy explicitly. Keploy would extract it from the docker spec.

docs: remove explicit docker network from readme

---

cmd/root.go

- Debug flag can be used anywhere in cmd.
Closes: #722
This would enable the debug flag to be passed after as well as before the subcommands.

refactor: debug flag anywhere in cmd

---

pkg/hooks/loader.go
pkg/proxy/integrations/httpparser/httpparser.go
pkg/proxy/util/util.go
pkg/util.go

- The recorded content length is different for the gzipped response.
Updates the content-length header of response in test mode.

fix: fix the content-length header of http response

---

pkg/proxy/integrations/httpparser/httpparser.go

Keploy fails to record testcases when the application is using the expect header.
Closes: #746 
I have added support for the expect header in Keploy. Now if the server encounters this header, it writes it to the destination connection first before reading the entire request, and only if the destination connection sends a 100-continue response, we read the entire request and then send it to the destination.

fix: added support for the expect header in Keploy

---

pkg/proxy/proxy.go

- #748 
- Add caCertPath and storepass flags to find for the right ca certificate in different java versions. 
`NA`

fix: import ca in case of different java version

---

Dockerfile

docker-compose is an independent binary, and is not shipped with Docker Engine. Hence, just like you cannot run non-statically C++ applications without their dependency inside docker containers, you also cannot run docker-compose commands unless you've installed it inside the environment. This PR adds suppport to install the plugin.
Closes: #702 ]

Add support for invoking commands via docker-compose

---

cmd/serve.go
pkg/proxy/proxy.go
pkg/service/record/record.go
pkg/service/serve/serve.go
pkg/service/serve/service.go
pkg/service/test/test.go

- #774 
- Add language flag in keploy serve command to identify when to search for java home in proc file system.
- Now if the language is java and keploy is running via serve command, then only proc file system would be searched to find the exact java home related to the process id.
`NA`

fix: fetch java_home from proc file system

---

pkg/proxy/integrations/httpparser/httpparser.go

1. If there is a client timeout during the handling of expect header, Keploy will not be able to get the body of the request.
2.  Sometimes when the req/ res is chunked, the last 0 chunk is read with the second last chunk itself, so the server goes in an infinite loop. Instead the 0 chunk should be read as a seperate chunk and when that is met, the loop should be broken.
Closes: #768 
Update the chunk handling functions to only read the number of bytes as specified in the size of the chunk. Reading the body of the req as soon as we send the 100-continue header to the client.
NA

fix: updated chunking mechanism and handled  expectation header issues

---

pkg/proxy/integrations/httpparser/httpparser.go

Whenever the server is not able to send the response body, Keploy throws a segmentation fault error. Instead it should handle the error in advance and not try to read the body if it is empty or doesn't exist.
Closes: #796 
We peek the parsed response body before reading it to make sure it is not empty. If it is, then we do not read the body and continue with the rest of the function.

refactor: Improved error handling for parsed response body

---

pkg/hooks/loader.go

-Recursively kills the child process started by the application.
Closes: #799
Instead of just killing the PID of the application we kill the child processes started by the application as well.
* Approach 1: PGID-Based Termination
This method involves identifying and terminating all processes sharing the same Process Group ID (PGID) as the user application. While this approach can efficiently kill all processes within the same group simultaneously, it presents a significant risk: it may inadvertently terminate unrelated processes—possibly even the parent processes—since they share the same PGID as the target application. Consequently, this approach is not recommended as it does not guarantee the isolation of the user application's processes and may lead to unintended system disruptions.
* …

fix: cleanup all the child processes started by app

---

cmd/serve.go
cmd/test.go
pkg/proxy/proxy.go
pkg/service/serve/graph/resolver.go
pkg/service/serve/graph/schema.resolvers.go
pkg/service/serve/serve.go
pkg/service/serve/service.go
pkg/service/test/service.go
pkg/service/test/test.go
pkg/util.go

- Test run gets blocked in case of failed outgoing call from user application
Closes: #815
Put a timeout on client do which makes call to user application, in case the call fails we would proceed further and other tests are performed successfully

fix: adding timeout to handle http timeout

---

cmd/mockrecord.go
cmd/mocktest.go
cmd/root.go
pkg/hooks/connection/factory.go
pkg/hooks/loader.go
pkg/platform/interface.go
pkg/platform/yaml/utils.go
pkg/platform/yaml/yaml.go
pkg/proxy/integrations/mongoparser/mongoparser.go
pkg/proxy/integrations/postgresParser/utils.go
pkg/service/mockrecord/mockrecord.go
pkg/service/mockrecord/service.go
pkg/service/mocktest/mocktest.go
pkg/service/mocktest/service.go
pkg/service/record/record.go
pkg/service/serve/graph/schema.resolvers.go
pkg/service/serve/serve.go
pkg/service/test/test.go

Add support for recording stubs using keploy v2 for using in unit tests
Closes: #726 
1. decoupled path from hooks and attached into yaml .
2. Remove config.yaml and added them in mocks.yaml.
3. create two commands :
sub cmd : mockRecord  flags : path, mockName, pid
sub cmd : mockTest  flags : path, mockName, pid
In both the commands pid of the running unit test is given and accordingly other flag are given by the user . In mockRecord we take in mockName name, rather than randomly creating one session and we store only mocks over there. tests will not be created as unit tests don't hit handlers they hit the handler functions. Similarly, for mockTest mockName name is taken and only those mocks are loaded.
In this way we can support recording stubs in unit tests
Tested using gin-mongo app …

Add support for recording stubs in unit tests

---

pkg/hooks/launch.go
pkg/proxy/proxy.go

- Keploy not able to generate test cases in docker environment.
Closes: https://github.com/keploy/keploy/issues/833
- Set proxy port field of hook in boot proxy function.
`NA`

fix: wrong new proxy port sent to kernel

---

pkg/proxy/integrations/httpparser/httpparser.go

When a client tries to make another request on the same connection, it is not able to do so because Keploy's http parser closes the client connection after one the request gets completed or there is an error.
When the server a 503 response, it also sends a small body along with it, but Keploy is currently not able to record that.
Closes: #824 #825 #836
Added a for loop for connection pooling in the http parser and also handled EOF in the chunked requests and chunked responses.

[bug]: Fixed retry and body parsing issues

---

pkg/hooks/loader.go
pkg/hooks/ringBufReader.go
pkg/platform/yaml/yaml.go
pkg/proxy/integrations/mongoparser/mongoparser.go
pkg/proxy/proxy.go
pkg/proxy/util/util.go

- Clean the exit loggs of Keploy CLI cmds.
Closes: #846 
Ignores the already closed error for the ringbuffer of eBPF during exit of Keploy CLI commands. And closes the existing client connections of proxy server when server is stopped during exit. Adds check before trying to kill the process with pid to filter unwanted error.

fix: update the exit loggs to ignore unwanted errors

---

cmd/mockrecord.go
cmd/mocktest.go
cmd/root.go
cmd/serve.go
pkg/hooks/launch.go
pkg/hooks/loader.go
pkg/models/testrun.go
pkg/service/mockrecord/mockrecord.go
pkg/service/mocktest/mocktest.go
pkg/service/record/record.go
pkg/service/serve/serve.go
pkg/service/test/service.go
pkg/service/test/test.go

1. Occasionally when userApp don't run properly or when user command is not proper , that error is not logged and Keploy also doesn't stop.
2. Few commands like serve and mockerRecord should be shown to user when user uses --help command.
3. Test report doesn't contain parameter test-set which it belongs to , So this may cause a problem if user want to backtrack from test report to test.
Closes: [#855](https://github.com/keploy/keploy/issues/855)
1. To fix userApp error problem following changes are made - 
There can be three type of errors from userApp 
i) UserInterrupt (Keploy will be killed by user and following …

fix: log errors and stop user app

---

pkg/platform/yaml/yaml.go

Closes: #873
The name of test case is inside `tcsName` variable. I have updated the arguments of Logger.info function to pass `tcsName`. 
N/A
| ![image](https://github.com/keploy/keploy/assets/91385321/83a2a81c-37c8-4b93-8c5d-8a8936abae21) | <b>![image](https://github.com/keploy/keploy/assets/91385321/84b9c874-902b-4f0f-a9c3-696d7fa479d2)</b> |

fix: empty testname when capturing the testcase

---

pkg/hooks/launch.go
pkg/service/record/record.go
pkg/service/test/test.go

Closes: #906 
Added stopper in record and test service
| <img width="1105" alt="Screenshot 2023-09-28 at 10 16 56 AM" src="https://github.com/keploy/keploy/assets/72094895/7f1036c5-47fc-4b58-b577-8b779493b698"> | <img width="1110" alt="Screenshot 2023-09-28 at 10 23 23 AM" src="https://github.com/keploy/keploy/assets/72094895/07048177-b51e-4820-82ec-0dd6c6da9db5"> |

Implement stopper in service layer

---

pkg/clients/clients.go
pkg/clients/docker/docker_client.go
pkg/hooks/launch.go
pkg/hooks/loader.go

Closes: #708 
Earlier after stopping keploy, it used to stop the docker container but not remove it. Now, the container will be stopped and removed.

stop and remove docker container

---

.vaunt/config.yml

N/A
Fixing the vaunt.config yaml.  There is a whitespace issue causing the yaml to not parse correctly.  Ran this through yamllint to verify.  Also removed extra "in" on last condition.
N/A
N/A
N/A

fix: yaml error and condition typo in vaunt.config

---

pkg/proxy/integrations/postgresParser/postgres_parser.go
pkg/service/serve/graph/resolver.go
pkg/service/serve/graph/schema.resolvers.go

- When I run multiple test-sets in test with the unit test integration, then the http requests are triggered before the user application is restarted.
Closes: #918 
There is a `firstRequestDone` variable which is used to assign the delay to 1 for the simulation of requests. This PR removes that boolean so that the requests are triggered after the user application has been restarted in the unit-test integration. Also fixes the postgres issue to get the updated mocks each time before reading the next requests from postgres client.
Tested changes with the go-test library.
NA

fix: adds delay for the second test-set in serve cmd

---

pkg/hooks/launch.go
pkg/hooks/loader.go
pkg/service/mockrecord/mockrecord.go
pkg/service/mocktest/mocktest.go
pkg/service/record/record.go
pkg/service/serve/serve.go
pkg/service/test/test.go

Closes: #938
1. Removed stopper from hooks and using it only in cmd layer
2. Added checks before stopping hooks and proxy for both stopping due to interrupt and stopping forcefully due to app error. So that only one gets executed.
3. Added a logger in case of command error.

fix: remove stopper from hooks

---

pkg/service/record/record.go

fix: remove channel from stopper 

---

pkg/hooks/connection/factory.go
pkg/platform/yaml/yaml.go

Closes: #880
Added the code to fetch the value from key: Keploy_Test_Name passed in the header of the request, and changed the value of `tcsName` with the value of our key since the variable is passed to the write .
N/A
| **![image](https://github.com/keploy/keploy/assets/91385321/31510761-896d-4a31-a946-c559ad7679ab)** | <b>![image](https://github.com/keploy/keploy/assets/91385321/b9bd09f6-73b3-42ea-b7eb-644707d3df19)</b> |

feat: option to name test cases

---

cmd/record.go
pkg/hooks/launch.go
pkg/service/record/record.go

Closes: #962 
1. Added checks to channels 

fix the channels communication between go routine in starting app via docker

---

.github/workflows/go.yml
.github/workflows/main.yml
.github/workflows/sample-run.yml

Closes: #986 
support for architecture came in [#253](https://github.com/actions/setup-go/pull/253)

Fix: check build for arm architecture

---

keploy.sh

- In docker installation, echo was there 2 times and also there was no need to add link in that.
- Remove links in the echo output (where docker is not installed and takes input to install)
`NA`

fix: docker installation for macos in installation script

---

pkg/proxy/integrations/genericParser/util.go

fixed matching algorithm

---

.github/workflows/docker-publish.yml
Dockerfile
goreleaser.yaml
main.go

Closes: #1029
There are 3 different scenarios where the version should be appeared in CLI output
1. When user runs released binary of keploy
2. When user runs released docker of keploy
3. When developer runs keploy in local by cloning keploy (docker as well as binary)
i) The 3rd scenario is nearly impossible because, when a developer forks keploy repository the release tags aren't pulled into the fork by default. So it is not possible to get the tags/version. I have tried multiple ways like 
--Pulling tags through code in main.go and using them but I found that we can't just pull tags but commit will also be pulled with the tags which will mess developer repo.
--Doing a request to keploy repo with each commit in dev repo and seeing if there is a tag associated …

Add version in binary and docker 

---

pkg/hooks/connection/factory.go
pkg/hooks/connection/tracker.go
pkg/models/http.go
pkg/models/mock.go
pkg/platform/yaml/model.go
pkg/platform/yaml/spec/generic.go
pkg/platform/yaml/spec/grpc.go
pkg/platform/yaml/spec/http.go
pkg/platform/yaml/spec/mongo.go
pkg/platform/yaml/spec/postgres.go
pkg/proxy/integrations/genericParser/genericParser.go
pkg/proxy/integrations/grpcparser/grpc_parser.go
pkg/proxy/integrations/grpcparser/stream_info_collection.go
pkg/proxy/integrations/httpparser/httpparser.go
pkg/proxy/integrations/mongoparser/mongoparser.go
pkg/proxy/integrations/postgresParser/postgres_parser.go
pkg/service/test/test.go
pkg/service/test/util.go

- On deletion of test cases, test cases mismatch with their respective mocks which caused inconsistency in the test mode
Closes: #916
Added the support for timestamp. Now, mocks will be filtered if it lies inside the test case's request and response timestamp

added timestamp support for test mode

---

pkg/proxy/integrations/genericParser/util.go
pkg/proxy/integrations/postgresParser/utils.go

removed repititve function definitions

---

Dockerfile
cmd/root.go
goreleaser.yaml
keploy.sh
main.go
pkg/platform/telemetry/telemetry.go
utils/utils.go

Currently a hardcoded version is injected into sentry . Need to inject correct keploy version
Updated the location of keploy logs and deleting the logs as soon as keploy stops. Also removed unncessary logs from the utils package, also updated the version updating mechanism

fix: Removed unneccessary logs and updated the version for sentry

---

cmd/examples.go
keploy.sh

- Examples added for one click install
Closes: #1052
Adding examples for custom and one click install setup

add:one click install example

---

pkg/proxy/integrations/mongoparser/mongoparser.go
pkg/proxy/integrations/mongoparser/operation.go

- Test fails for the mongo call which have have a substring containing ` }` in the sectionSingle of OpMsg like:
``` "errmsg":"Error in specification { background: true, name: \"merchant_id_text_url_text_hash_hashed\", key: { merchant_id: \"text\", url: \"text\", hash: \"hashed\" } } :: caused by :: Can''t use more than one index plugin for a single index." ```.
Due to which keploy is not able to extract and encode into the message back to the binary Mongo wire message.
The decode function is not able to distinguish the closing braces of the string json and sectionSingle, so used the prefix and suffix in place of regex to extract the document correctly
Tested the changes with gin-mongo API. And the problamatic example of OpMsg in …

fix: updates the decode function for OpMsg section

---

pkg/proxy/integrations/httpparser/httpparser.go

- Keploy throws i/o timeout while reading http response for the 2nd and subsequent mocks.
Closes: #1062 
- Added a return statement when there is `Transfer-Encoding:chunked` request/response but the complete request/response (including body) comes in the initial packet only.
`NA`

fix: i/o timeout while reading http response

---

pkg/hooks/connection/tracker.go

Added a flag for recording the request timestamp

added flag for req timestamp

---

pkg/proxy/integrations/postgresParser/postgres_parser.go

- there is no check before accessing the network packet buffer index to slice the buffer.
Closes: #1092
adds a check before accessing the buffer index.

fix: adds a check before accessing the buffer index

---

pkg/proxy/integrations/mongoparser/mongoparser.go
pkg/proxy/integrations/mongoparser/scramAuth.go
pkg/service/test/test.go

- The authentication mocks for mongo are captured once and filtered on the basis of captured time before simulation, due to which the testrun fails for multiple testcases in the test-set. 
- The mocks are fetched and stored locally before the read blocking call due to which the matching of requests fails since there are no mock requests to match with. This results in test run failure
Closes: #1103 
- Updates the authentication calls in mongo protocol to config calls for the database connection.
-  Fixes the issue of accessing an empty array after simulation by fetching tcs mocks after connection.read call
Tested the changes with the gin-mongo sample which connects to documentDB database.

fix: updates the auth calls to config for mongo

---

pkg/proxy/asset/setup_ca.sh
pkg/proxy/proxy.go

- Unable to handle TLS connection in case of Python virtual env, in the regular environment it's working.
Closes: #1107 
- Set an environment variable `REQUESTS_CA_BUNDLE` in the case of Python to use our custom CA for TLS connections.
`NA`

fix: tls connection in python

---

pkg/proxy/integrations/httpparser/httpparser.go

Chunked http integration is failed because of the timeout implemented at the httpparser .
Closes: #1127
The server can take its own time to send the chuck response . There is no time limit in it. But we have introduced a time limit of 5 seconds in our proxy which cause the issue mentioned above. Removed the time out implementation to resolve this issue.
I have tested the sample apps provided in the issue and everything worked out fine after implementing changes.
NA

fix: remove timeout from chunking

---

pkg/proxy/integrations/mongoparser/mongoparser.go
pkg/proxy/proxy.go
pkg/service/test/test.go
pkg/service/test/util.go

- Fails in test mode for a documentDB application.
Closes: #1129 
Assigns the value of the mongoPassword configured via the test cmd flags to the mongoParser in order to handle the scram authentication.
I have recorded and tested some APIs of a go and java application which make external calls to DocumentDB.

fix: sets the auth password for mongo to handle scram authentication

---

pkg/hooks/launch.go
pkg/service/record/record.go
pkg/service/serve/serve.go
pkg/service/test/test.go

-  Refactoring of error handling in keploy serve.
Closes: `NA`
- Made a new error type to distinguish errors between server-running & non-server-running commands (For eg: `mvn test`, `npm test`, `go test` etc.
`NA`

refactor: error handling when running keploy serve

---

pkg/service/generateConfig/generateConfig.go

Closes: #1145 
added chmod function to change permission for keploy-config file

fix: config perm

---

pkg/proxy/integrations/postgresParser/postgres_parser.go

fix: payload issue for data row packet in postgres

---

pkg/service/generateConfig/generateConfig.go

- Add filter when generating keploy-config.yaml
Closes: N/A
Added filters object when generating keploy-config.yaml
NA
NA

Add filter when generating keploy-config

---

pkg/platform/fs/tele.go
pkg/service/mockrecord/mockrecord.go
pkg/service/mocktest/mocktest.go
pkg/service/record/record.go
pkg/service/serve/graph/schema.resolvers.go
pkg/service/serve/serve.go
pkg/service/test/test.go
utils/utils.go

- When there is a new user created, we see a nil pointer captured by the handlePanic function.
Closes: #1191 
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know
- I've used the right logger where the core has been initialized, Because in cases where we use Any(). It can fail to check the type if the core is nil.
`NA`

fix: handle panic in logger 

---

pkg/service/test/test.go
pkg/util.go

When port is changed in the test case after `keploy record` is run, the `keploy test` produces a report which shows that the status is `Running` instead of `Failed`.  
Closes: #1169
- A small code change in `pkg/util.go` to handle cases where the returned HTTP response is null, to return a valid `models.HttpResp` to make sure that this case can be accurately classified as Failed in `pkg/service/test/test.go` when compared with the actual response that needed to be returned. 
- A condition addition in an if block in `pkg/service/test/test.go` to check if response is nil before doing an early return without running `testHttp`.
`NA`
`NA`
`NA`

fix: modified return of nil response for HTTP Connection Error

---

cmd/record.go
cmd/test.go

-refactored logs from print to logger
Closes: #1202
Updated the codebase to utilize logging methods for generating logs instead of relying on print statements.
| 
| 
|

refactor: logs in record and test commands

---

.github/ISSUE_TEMPLATE/--bug-report.yaml
.github/ISSUE_TEMPLATE/--documentation-update.yaml
.github/ISSUE_TEMPLATE/--feature-request.yaml

- Added "Writers-Program" Option to Issue Templates
Added the "Writers-Program" repository option to the existing dropdown selections in the issue templates. Updated relevant files/templates to incorporate this change and ensure consistency across all templates.
NA - This is a template modification, no new test cases are required.
NA - The modification aims to enhance the user experience and does not introduce any unusual behavior.

feat: Added writers-program option in Issue template.

---

pkg/proxy/integrations/postgresParser/postgres_parser.go
pkg/proxy/integrations/postgresParser/utils.go

Some applications are making more connections with Postgres during test mode than it did during record mode. So there are also more auth requests from the application during test mode, but we didn't have sufficient auth packets - which leads to auth failures in some requests.
**Why did this happen?**
Since the application is able to execute much faster during testmode, it tries to increase the connection pool to handle higher request throughput. This seems to be normal application behaviour for psycog3
Fix: We are making database connection related properties like authentication re-useable to handle cases where more connections are created during test mode.
Please describe the tests(if any). Provide …

feat(pg-parser): ignore deletion of startup request mocks during match

---

go.mod
go.sum
pkg/hooks/connection/tracker.go
pkg/hooks/loader.go
pkg/hooks/ringBufReader.go
pkg/hooks/settings/clock.go
pkg/models/mock.go
pkg/platform/yaml/yaml.go
pkg/proxy/integrations/postgresParser/postgres_parser.go
pkg/proxy/integrations/postgresParser/utils.go
pkg/service/test/test.go
pkg/service/test/util.go

- #1354
- #1353
Closes:  #1354 and #1353
1. Generic mocks are not sorted based on the timestamp of the request to significantly improve accuracy of matching. 
2. Testcase Response is not recorded as soon as the server starts sending data. 
3. The Mock datastore now has sorting information to ensure that the mocks are matched according the timestamps. 
4. The mocks now also have an id to ensure correlation with the logs. 
5. We have made Postgres use ConfigMocks by default instead of TCS (Data mocks) since it's hard to pinpoint exact request related mock. This would be further improved in a future version. 
6. Extra Debug and info logs added for better visibility to debug future issues.

fix: sorting of config mocks acc to req timestamp

---

pkg/platform/yaml/yaml.go

- #1356
Closes: #1356
Add support for v1beta2 used in some older keploy releases and also older Postgres mocks.

fix: add support for v1beta2 and old postgres mocks

---

pkg/proxy/integrations/httpparser/httpparser.go

- Keploy HttpParser fails to handle when HTTP headers also come in chunks
Closes: https://github.com/keploy/keploy/issues/1346
- Our proxy operates as a TCP server rather than an HTTP server, making it possible for HTTP headers not to arrive in the first chunk. Our HTTP parser observed headers arriving in multiple chunks due to TCP fragmentation based on chunk length, especially when the sender buffer is smaller. I've implemented a fix to handle these header chunks until complete headers are received.
- I've refactored error handling, identifying cases where certain errors need to be propagated to the caller function.
- Addressed an issue with the HTTP mock response headers, where two content-length values were being received. Previously, the code used the `add` function, but it should …

fix: HTTP handling for partial header reception

---

pkg/hooks/connection/tracker.go
pkg/service/test/test.go

- Instead of using an array to save the response time reverted to set the response time of response only after the data is verified.
Closes: #1418
Because of maintaining an array of mock and picking the first element of the array we were unable to get certain mock files as a result of which  connection would end and test cases would fail.

refactor:setting time stamp for response only after verified response

---

pkg/hooks/loader.go
pkg/proxy/integrations/genericParser/genericParser.go
pkg/proxy/integrations/mongoparser/mongoparser.go
pkg/proxy/integrations/mysqlparser/mysqlparser.go
pkg/proxy/integrations/postgresParser/postgres_parser.go

Closes: #1463
Add checks to ensure user application isn't terminated before proceeding to stop the server

refactor:function name and checks

---

cmd/test.go

Closes: #1576
-Checks for the existance of the folder before granting access to it
-I tested it without testcases and with testcases.

[fix]: bug while keploy test in user app

---

pkg/clients/docker/docker_client.go
pkg/platform/telemetry/utils.go
pkg/proxy/integrations/httpparser/httpparser.go
pkg/proxy/proxy.go
utils/utils.go

Closes: #1587
I replaced deprecated io/ioutil package with io and os package.
https://pkg.go.dev/io/ioutil

fix: replace deprecated io/ioutil package

---

keploy.sh

fix: add network in linux installation script

---

cmd/test.go
pkg/graph/resolver.go
pkg/graph/schema.resolvers.go
pkg/graph/serve.go
pkg/graph/service.go
pkg/service/test/match.go
pkg/service/test/test.go
utils/utils.go

- filter to run specific test-set/testcases do not work for code coverages
Closes: #1611
Returns filtered test sets to the unit test frameworks and passes filtered testcases to the RunTestSets of test service
Tested the changes with junit test to capture code coverage.
NA

fix: adds test filter to the serve to generate code coverage

---

cli/util.go
pkg/platform/yaml/reportDb/reportDb.go
pkg/platform/yaml/yaml.go

refactor:context cancel in create yaml

---

pkg/hooks/loader.go
pkg/proxy/proxy.go

- Nil pointer exception when the code coverage fails to run user test cmd
Closes: #
Adds a nil check to avoid nil pointer referrence before closing the ebpf hooks

fix: adds a nil check before stopping the ebpf hooks

---

pkg/proxy/integrations/postgresParser/postgres_parser.go

refactor: make logs which doesn't effect test result to debug

---

pkg/hooks/launch.go

Removed redundant user and group id set on the app cmd which lead to failures if the user is not a sudoer.

fix: cmd failure if user is not sudoer

---

pkg/service/test/test.go

- Test mode fails for an API maing an external https call for fedora-39.
Closes: #1679 
Linux distros like fedora uses systemd-resolve for dns resolution which makes unix socket with the application due to which keploy is not able to redirect them to proxy in test mode. This results in test failure. This is handled by editing the nsswitch.conf of /etc in linux to not use resolve in test mode

fix: redirect dns calls by configuring nsswitch config file in linux

---

pkg/proxy/proxy.go
pkg/service/test/test.go

adds timeout to the destination connection request in proxy

fix: adds timeout to the destination connection request in proxy

---

cli/provider/cmd.go
cli/provider/service.go
utils/utils.go

- No need to validate root cmd flags.
- Removed unnecessary viper binding of root command flags because subcommand contains the persistent flags of root.
- Since each subcommand is validated, the persistent flags of root are also binded.
`NA`

chore: remove unnecessary binding of root cmd flags

---

cli/config.go
cli/mock.go
cli/provider/cmd.go
cli/provider/service.go
cli/record.go
cli/root.go
cli/service.go
cli/test.go
cli/update.go
config/default.go
main.go
pkg/service/tools/tools.go

- config as a parameter in the cmdConfigurator and serviceProvider makes difficult to implement enterprise config
Closes: https://github.com/keploy/enterprise/issues/162
the config is present in the function signature due to which different implementations of the interface is restricted to use the oss config type. This makes a challenge in the enterprise to add its own config type for enterprise flags. Thats why the config is now a member field of the struct that implements cmdConfigurator and serviceProvider interfaces.

fix(cli): adds config as a field in cmdConfigurator and serviceProvider 

---

.github/workflows/sample-run.yml
pkg/core/proxy/integrations/generic/decode.go
pkg/core/proxy/integrations/generic/encode.go
pkg/core/proxy/integrations/grpc/encode.go
pkg/core/proxy/integrations/http/decode.go
pkg/core/proxy/integrations/http/encode.go
pkg/core/proxy/integrations/mongo/encode.go
pkg/core/proxy/integrations/mysql/encode.go
pkg/core/proxy/integrations/postgres/v1/decode.go
pkg/core/proxy/integrations/postgres/v1/encode.go
pkg/core/proxy/util/util.go

ISSUE: 
When running keploy with multiple test-sets it throwing errors when closing application due to connection break
CHANGES:
1. removed closing dest conn twice
2. added eof check for error check in reading data from connection.

fix: ending errors while closing application

---

cli/provider/cmd.go
config/config.go
config/default.go
pkg/core/proxy/integrations/generic/match.go
pkg/service/replay/replay.go
pkg/util.go

**ISSUE** :
1. go coverage is not working because --coverage flag is now used for spinning graphQl server
2. Tried a go-app, generic mocks are not matching because of high similarity constant.
3. keploy test header which is added via test is causing diff in the test response because in a go-app headers in request getting repeated in the test response. 
**Changes**:
1. added new goCoverage flag
2. decreased similarity constant 
3. remove keploy test header as their is no use case as of now.
|        Original         | …

fix: go test coverage

---

cli/config.go
cli/provider/cmd.go
cli/record.go
cli/test.go

- fixes bug https://github.com/keploy/keploy/issues/1747
Closes: #1747 
- Remove the silencing of Record.
- Implement proper handling of ValidateFlags() calls.
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [x ] Code style update (formatting, local variables)

bug fix/1747. enable error logging for invalid flags

---

pkg/core/app/app.go
utils/utils.go

- lint issue in `main` branch due to unused parameter
- Removed `cmd` parameter in `interrupProcessTree` function
`NA`

fix: lint issue

---

pkg/core/proxy/integrations/postgres/v1/decode.go
pkg/core/proxy/integrations/postgres/v1/match.go
pkg/core/proxy/integrations/postgres/v1/util.go

- So I observed, that breaking it’s happening in case of streaming postgres requests by client in case of pooling .
const { Pool } = require('pg');
So currently keploy matches the request coming at the time test mode with the requests saved in the mock files . So what happening is pg client is streaming in a random order which is causing mismatch in the matching algorithm. 
for eg - in record it can give me requests in 4 chunks [P],[B],[D],[E] but in case it might give me in a single buffer or breaking in any other fashion.
So I solved it by merging all the requests in a single buffer both for the actual requests and the saved in the mocks for uniformity and matching. 
So any pattern will at last be compared as [P,B,D,E].
Closes: #1788 
A clear and concise description of what you have …

fix: make exact match work for chunked pg req

---

main.go
pkg/core/proxy/integrations/http/encode.go

- Fixed blocking of keploy after interrupt
Closes: #1802 
- Was not returning from the go routine when an error occurred while reading from the client connection.
`NA`

fix: blocking of keploy after interrupt while using http deps

---

pkg/core/proxy/integrations/generic/decode.go
pkg/core/proxy/integrations/generic/encode.go
pkg/core/proxy/integrations/grpc/encode.go
pkg/core/proxy/integrations/http/decode.go
pkg/core/proxy/integrations/http/encode.go
pkg/core/proxy/integrations/mongo/decode.go
pkg/core/proxy/integrations/mongo/encode.go
pkg/core/proxy/integrations/mysql/decode.go
pkg/core/proxy/integrations/mysql/encode.go
pkg/core/proxy/integrations/postgres/v1/decode.go
pkg/core/proxy/integrations/postgres/v1/encode.go
pkg/core/proxy/proxy.go
pkg/core/proxy/util/util.go
utils/utils.go

- Closing of keploy due to panic in parser
Closes: #1815 
- Added another Recover function to recover from parser and only close the active client and dest connection and return without canceling the global context.
`NA`

fix: closing of keploy due to panic in any parser

---

cli/provider/cmd.go
cli/test.go
config/config.go
config/default.go
pkg/core/proxy/integrations/http/decode.go
pkg/service/replay/replay.go
utils/utils.go

- go coverage not working without setting `GOCOVERDIR` explicitly.
Closes: https://github.com/keploy/keploy/issues/1813
- Set `GOCOVERDIR` implicitly if `goCoverage` is enabled.
- Handle custom path for coverage reports
`NA`

fix: go coverage in native

---

pkg/core/proxy/proxy.go
pkg/core/proxy/util/util.go
pkg/models/config.go

- Passthrough not working in case of failed matching of mocks
- Made a TLS connection if config is there for passthrough. 
`NA`

fix: pass through not working in case of https request

---

pkg/core/proxy/integrations/http/decode.go
pkg/core/proxy/integrations/http/match.go
pkg/core/proxy/integrations/postgres/v1/match.go
pkg/platform/yaml/mockdb/db.go

- Async matching was not supported in http.
Closes: #1831 
- Made all the HTTP mocks unfiltered mocks and also changed the implementation of current HTTP matching which was not robust earlier.
`NA`

feat: add support for async http matching

---

pkg/service/replay/absmatch.go

- The test bench broke due to this parameter.
- Add `Keploy-Test-Id` to header noisy in abs match.
`NA`

fix: add keploy-test-id header to noisy field in abs match

---

pkg/core/core.go
pkg/core/hooks/hooks.go
pkg/core/service.go

- DNS fails for the external calls in native and docker when the services are down
the eBPF code is dependent on the mode of keploy which is recieved from the user space code. But after the re-factor there were changes regarding the deprecation of the global mode state. Due to which the user space code is not sending the mode to eBPF code.

fix: fixes dns problem to redirect them to proxy in test mode

---

pkg/platform/yaml/testdb/util.go
pkg/service/replay/match.go
pkg/service/replay/utils.go

- [Global Noise failing due to case insensitive viper bindings](https://github.com/keploy/keploy/issues/1724)
Closes: #[1724](https://github.com/keploy/keploy/issues/1724)
Used lower case during comparison for body and header keys
NA
| **![Screenshot_20240508_110651](https://github.com/keploy/keploy/assets/73810056/bc94a581-4de1-4556-a740-dcb0b985aa10)** | <b>
</b> |

Globalnoise

---

cli/mock.go

NA
Closes: NA
Fixed a typo (ougoung -> outgoing) in the one-liner of the `mock` command which is displayed on keploy cli's help message.
Typo
NA
NA

fix: fix typo in cli/mock.go

---

pkg/service/record/record.go
pkg/service/record/service.go
pkg/service/record/utils.go
pkg/service/replay/replay.go
pkg/service/replay/utils.go
utils/utils.go

fix: fixed re-record for docker 

---

pkg/platform/yaml/mockdb/db.go
pkg/service/replay/replay.go
pkg/service/replay/service.go
pkg/service/replay/utils.go

add: support of custom mock name

---

pkg/core/proxy/proxy.go

Log warning in case of error if the CA injection fails so that rest of the code could work. 
eg: 
```
keploy test                             
▓██▓▄
▓▓▓▓██▓█▓▄
████████▓▒
▀▓▓███▄      ▄▄   ▄               ▌
▄▌▌▓▓████▄    ██ ▓█▀  ▄▌▀▄  ▓▓▌▄   ▓█  ▄▌▓▓▌▄ ▌▌   ▓
▓█████████▌▓▓   ██▓█▄  ▓█▄▓▓ ▐█▌  ██ ▓█  █▌  ██  █▌ █▓
▓▓▓▓▀▀▀▀▓▓▓▓▓▓▌  ██  █▓  ▓▌▄▄ ▐█▓▄▓█▀ █▓█ ▀█▄▄█▀   █▓█
▓▌                           ▐█▌                   █▌
▓
version: 2.1.0-alpha18
🐰 Keploy: 2024-05-26T12:05:10+05:30    WARN    Delay is set to 5 seconds, incase your app takes more time to start use --delay to set custom delay
🐰 Keploy: 2024-05-26T12:05:10+05:30    INFO    Example usage: keploy test -c "/path/to/user/app" --delay 6
🐰 Keploy: 2024-05-26T12:05:10+05:30    INFO    GitHub Actions workflow file generated …
```

fix: log warning in case of ca failures

---

cli/provider/cmd.go
config/config.go
config/default.go
main.go
pkg/core/proxy/integrations/generic/encode.go
pkg/core/proxy/options.go
pkg/core/proxy/proxy.go
pkg/core/proxy/util.go
pkg/core/proxy/util/util.go
pkg/models/instrument.go
pkg/service/record/record.go
pkg/service/replay/replay.go

- Support for global passthrough of external calls
Closes: https://github.com/keploy/keploy/issues/1919
- Add a flag to disable mocking in test mode. You can use it like, `keploy test -c "<appCMD>" --mocking=false`
- Move the Rerecord flag to only test in the cmd package.
`NA`

feat: add support for global passthrough in test mode

---

pkg/core/app/app.go
utils/utils.go

- Instead of killing children kill the container directly
- Wait for 25 second before sending sigkill
- Listen to docker events for 30seconds, if not killed log that application isn't killed
Closes: https://github.com/keploy/keploy/issues/1904

chore: kill docker container 

---

cli/provider/cmd.go
cli/provider/compat_linux.go
cli/provider/compat_others.go

Currently due to the Linux kernel version check, keploy could no longer be compiled on macOS.

chore: fix compilation errors on macos

---

.github/workflows/release.yml

change the runner from ubuntu to macos to ensure macOS bianries can be signed. we use `gon` for signing macos binaries and it requries macOS

ci: use macos github action for goreleaser

---

.github/workflows/release.yml

This PR enables the gon installation action and the apple signing step to enable binaries to be tested.

ci: enable gon installation and apple signing for release

---

.github/workflows/release.yml

We need to change the version of gon because apple has stopped accepting `altool` and now uses a new tool which current version of gon doesn't support. 
ref: https://github.com/mitchellh/gon/pull/72

ci: change the version of gon used

---

pkg/core/app/app.go
pkg/models/testrun.go
pkg/service/replay/replay.go
utils/utils.go

- Allow user to run pre/post script for each test-set.
Closes: https://github.com/keploy/keploy/issues/1953
- Refactored the cmd execution logic 
- Add support for pre/post scripts to run before/after each test-set.
`NA`

feat: add support for running pre/post scripts of test-set

---

pkg/core/proxy/integrations/postgres/v1/decode.go
pkg/core/proxy/integrations/postgres/v1/match.go

Prisma was failing in test mode because of incorrect prepare statement matching
Added check for prepare statments of type 's*' along with 'S_*' as well.

fix: added check for prisma prepare statement matching

---

pkg/platform/yaml/testdb/util.go
pkg/service/replay/match.go

1. Noise in the reports was wrong because we are explicitly converting noise into lower case. Removed this.
2. Remove auto-detection of noise while updating test case because when we remove noise, still the noise is getting appended.

fix: denoise bugs

---

cli/provider/core_service_linux.go
pkg/core/hooks/hooks.go
pkg/core/hooks/util.go

- DNS bug in macOS
Closes: https://github.com/keploy/keploy/issues/2006
- In the case of docker, the ipv6 is already disabled but still in newer versions of Java, ipv4 mapped ipv6 is used hence added this support.
- Fix lint issue.
`NA`

fix: dns bug in macOS

---

pkg/service/replay/replay.go

1. Ignore testCase is ignoring complete testSet.
2. Need add one more condition for skipping testSet.

fix: ignore testCase bug

---

config/default.go

Closes: #2038 
Remove the indocker flag 
NA

Fix keploy gives error for gin mongo when recorded with docker compose

---

pkg/core/proxy/integrations/postgres/v1/match.go

Closes: #2134
RCA:
1. The API broke due to incorrect mocking in Postgres parser.
2. The timestamp fields in the request buffer was different and it wasn't matched in exact match.
Changes:
1. Added logic to ignore timestamp field matching.

fix: postgres parser bug

---

cli/provider/cmd.go
config/config.go
pkg/service/orchestrator/rerecord.go
pkg/service/replay/replay.go
utils/utils.go

- #2184 
Closes: #[2184]
- Added a host flag in test as well re-record for replacing the url host before simulating the tests.
- Now user can replace the request host by using `--host` flag of keploy

feat: introduce flag to replace http host

---

pkg/core/proxy/integrations/mysql/recorder/query.go
pkg/core/proxy/integrations/mysql/wire/decode.go
pkg/core/proxy/integrations/mysql/wire/util.go

- This PR fixed the condition where we read the `EOF` packet after the column definition packet in TextResultSet.
- https://github.com/keploy/keploy/issues/2023
Closes: https://github.com/keploy/keploy/issues/2214

fix: missed reading eof packet leads to blocked client conn

---

pkg/platform/yaml/configdb/user/db.go

Issue :  If machineId is not present in machine(docker containers/ Kubernetes) currently keploy stops execution
solution: Ignore machineId if not present.

fix: ignore machine id if not present

---

cli/provider/service.go

Taking the version from the utils package instead of the config
Currently the version was coming empty because it was being taken from the config. Now taking it directly from utils so it will never be empty.

fix: version problem in tele

---

pkg/core/proxy/integrations/mysql/recorder/query.go
pkg/core/proxy/integrations/mysql/replayer/match.go
pkg/core/proxy/integrations/mysql/wire/util.go

- This PR fixes the issue when during record mode, in response to `COM_QUIT` packet server doesn't send a response and closes the connection.

fix: handle eof in case of COM_QUIT

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
HACKTOBERFEST_GUIDE.md
README-UnitGen.md
README.md
READMEes-Es.md

As of now the Slack Joining URLs which are present in our guide and Readme are not accessible by the new people since it is asking for `*@keploy.io` domain email. This is because Slack has limit of 400 people who can join via same URL.
This pr fixes the slack url current present in our guides and readme.

feat: update slack urls

---

pkg/core/proxy/integrations/mysql/recorder/conn.go
pkg/core/proxy/integrations/mysql/replayer/conn.go
pkg/core/proxy/integrations/mysql/wire/phase/conn/authSwitchRequestPacket.go
pkg/core/proxy/integrations/mysql/wire/phase/conn/authSwitchResponsePacket.go
pkg/core/proxy/integrations/mysql/wire/util.go
pkg/models/mysql/const.go

- This PR adds a fix for handling `AuthSwitchRequest` in the MySQL parser when server wants to switch the auth mechanism after a disagreement with the client default mechanism. 
- https://github.com/keploy/keploy/issues/2268

fix: handling of authSwitchReq during auth mechanism switch

---

pkg/core/proxy/integrations/mysql/replayer/match.go

- This PR fixes the matching logic of `HandshakeResponse41` packet in MySQL parser

fix: matching of handshakeResponse in mysql

---

pkg/core/proxy/integrations/mongo/decode.go
pkg/core/proxy/integrations/mongo/operation.go
pkg/core/proxy/integrations/mongo/util.go

Fix for Mongo Auth failure due to usage of old client driver which led to usage of legacy wire protocol.
1. Issue can be reproduced by this branch - https://github.com/keploy/samples-java/tree/mongo_nug/spring-boot-mongo
2. With the latest mongo wire protocol/driver the auth considering `saslStart` and `saslContinue` is done by `OP_MSG` - supported by our parser
3. In a bit lower versions `saslStart` is done by `OP_QUERY` and `saslContinue` by `OP_MSG` - supported by our parser
4. In more lower versions/legacy version `saslStart` and `saslContinue` are done by `OP_QUERY` - not supported by our parser
5. These some times depend on the drivers and specific language drivers also
6. Fixed this by adding `saslContinue` support in `OP_QUERY` in the mongo parser.
sample queries:
` query: …

feat: add support for legacy mongo protocol

---

keploy.sh

Adds platform flag in one click install to run the installation in a particular shell.
Command :- `source keploy.sh -noRoot -platform bash`

feat: added new flag in one click install script

---

cli/provider/cmd.go
cli/provider/service.go
config/config.go
pkg/service/utgen/assets/test_generation.toml
pkg/service/utgen/gen.go
pkg/service/utgen/prompt.go

Adds additional test gen command
Closes: https://github.com/keploy/keploy/issues/2299
- [] Bug fix (non-breaking change which fixes an issue)
```
keploy gen  --source-file-path="/Users/shivamsouravjha/samples-typescript/express-mongoose/src/routes/routes.js"  --test-file-path="/Users/shivamsouravjha/samples-typescript/express-mongoose/test/routes.test.js"   --test-command="npm test"  --coverage-report-path="/Users/shivamsouravjha/samples-typescript/express-mongoose/coverage/cobertura-coverage.xml"  --llmApiVersion "2024-02-01" --llmBaseUrl "http://localhost:8089" --max-iterations "5" --additional-prompt "make sure all the generated testcases are only for student endpoint."
```

add: additional prompt for test gen

---

pkg/core/proxy/proxy.go

[fix]: keploy hangs if proxy port is already in use
Closes: #1705
- [] New feature (non-breaking change which adds functionality)

[fix]: keploy hangs if proxy port is already in use

---

pkg/core/proxy/integrations/postgres/v1/util.go

Fixes [https://github.com/keploy/keploy/security/code-scanning/149](https://github.com/keploy/keploy/security/code-scanning/149)
To fix the problem, we need to ensure that the integer value obtained from `strconv.Atoi` is within the bounds of `uint32` before performing the conversion. This can be done by adding a check to ensure the value is non-negative and does not exceed the maximum value of `uint32`.
1. Use `strconv.ParseUint` instead of `strconv.Atoi` to directly parse the string into a `uint32` value.
2. If using `strconv.Atoi`, add a check to ensure the parsed integer is within the bounds of `uint32` before converting it.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Fix code scanning alert no. 149: Incorrect conversion between integer types

---

pkg/core/proxy/integrations/http/match.go

Issue - Few applications which have http calls as outgoing inherit the headers from incoming api call. So in test mode kpeloy adds few headers in the http incoming api call for various reasons like deduplication etc. Due to this these headers are inherited by the outgoing http calls and mock matching is failing.
solution - remove these particular headers from matching.

fix: remove comparison of keploy header in http parser

---

pkg/platform/http/agent.go

This PR updates the Setup function to handle context-aware cancellation gracefully. Key improvements include:
Starting the agent only if not already running, with support for context cancellation during startup (e.g., Ctrl+C).

fix: Setup Function with Context-Aware Cancellation for Agent Startup

---

main.go
pkg/service/utgen/gen.go

- This fixes the iteration count in ut-gen that is used in the events.
- Earlier coverage update event and test-generation event iterations were out of sync.
`NA`

fix: iteration count in ut-gen events

---

keploy.sh

ISSUE - https://github.com/keploy/keploy/issues/2448
Resolution - ARCH variable was accidentally removed from installation script in this PR - https://github.com/keploy/keploy/pull/2441/files , added it again.

fix: arch var in installation script

---

.github/workflows/test_workflow_scripts/golang-docker-compose.sh

This PR fixes an issue in the Keploy test script where the log file reference in the grep commands was incorrect. In the original script, the grep commands were checking for errors or warnings in a log file that did not exist (${test_container}.txt), while the actual log file was being saved as ${test_container_logs}.txt.
Closes: #2460 

fix: incorrect log file reference in golang-docker-compose test script

---

pkg/util.go

fix a bug
btw, there should add a `defer httpResp.Body.Close()` 
I create a linter to detect code that returns a non-relevant nilness error bug. I checked the top 1000 GitHub Go repositories and found this, all result listed in https://github.com/alingse/sundrylint/issues/4

fix: check `errReadRespBody != nil` but return a nil value error `err`

---

pkg/service/utgen/utils.go

I have added Python to `utgen` which is done by specifying `testDir`.
- related: https://github.com/orgs/keploy/discussions/2466
I have verified that the following commands succeed using pytest-cov.
```
$ keploy gen \
--testDir="./" \
--coverageReportPath="./coverage.xml" \
--testCommand="uv run pytest --cov ./ --cov-report xml" \
--model="gpt-4o-mini"
```
I am still getting used to contributing to this repository. Please point out any other tests needed.

add python to utgen

---

pkg/service/replay/replay.go

Currently we have added a check if the testset config is not present and the error is `no such file or directory` we are continuing the execution without it. But on windows if the testset config is not present it throws different error `The system cannot find the file specified` hence stopping the execution flow. 

fix: basepath replay not working on windows

---

cli/provider/cmd.go
cli/provider/util.go
pkg/platform/yaml/yaml.go

This pull request includes several changes to improve error handling and logging within the codebase. The most important changes include enhancing the validation process for command flags, refining error messages, and improving the creation of YAML files.
Enhancements to error handling and logging:
* [`cli/provider/cmd.go`](diffhunk://#diff-a5137720b20dbcb8f3812a18d16b1fc9a65835f982accc5259aac757fface66eR376-R383): Added detailed logging for missing required flags and provided example usage instructions when the `-c` flag or `appCmd` is missing.
* [`cli/provider/util.go`](diffhunk://#diff-12646fb9c2de3aa23c78a401b55be0a7466c314d84a0b48e1945de8cba228cc4L13-L18): Removed redundant logging in the `noCommandError` method to streamline error handling.
* …

refactor: allow write tests afters context cancelled

---

cli/provider/cmd.go

This pull request includes changes to the `ValidateFlags` function in the `cli/provider/cmd.go` file. The main modification involves moving the logic that handles the app command to a different location within the function. This change ensures that the command type is set before checking if the app command is already running.
Reorganization of logic in `ValidateFlags`:
* Moved the block of code handling the app command to a different location within the `ValidateFlags` function. This ensures that the command type is set before checking if the app command is already running. [[1]](diffhunk://#diff-a5137720b20dbcb8f3812a18d16b1fc9a65835f982accc5259aac757fface66eL586-L592) [[2]](diffhunk://#diff-a5137720b20dbcb8f3812a18d16b1fc9a65835f982accc5259aac757fface66eR652-R658)
(Provide a description …

fix: validating flag when command is not provided

---

.github/workflows/go.yml

It defines only a specific version of `@semantic-release/exec`. Because there are breaking changes in version 7
https://github.com/semantic-release/exec/releases/tag/v7.0.0
As you can see in the link above that `@semantic-release/exec` `v7.0.0` has breaking changes and they have converted the plugin to `ES module`. But our system is expecting a `CommonJS module`. 
So this PR fixes version to `6.0.3` until we have  stronger reason to upgrade it further.
Closes: #2544
None

fix: @semantic-release/exec version to 6.0.3

---

pkg/core/proxy/integrations/mongo/mongo.go

Closes: #2576
Changes:
1. This is happening as we don't save all the config mocks into the mock file we rule out them as duplicates(not exactly duplicate) but when clustered mongo is used we need them.
2. Removed the code where we discard duplicate mocks(not exactly duplicate)

fix: missing mongo config mocks

---

pkg/service/utgen/ai.go

This pull request introduces a new feature to the `pkg/service/utgen/ai.go` file by adding a `ReasoningEffort` parameter to the `CompletionParams` struct. This change allows for specifying the level of reasoning effort required for AI completions.
Key changes:
* Added `ReasoningEffort` field to the `CompletionParams` struct to allow specifying reasoning effort levels.
* Defined a new `ReasoningType` type and constants for `HighReasoning`, `LowReasoning`, and `MediumReasoning` to represent different levels of reasoning effort.

feat: add reasoning effort type for o1 model

---

.github/workflows/test_workflow_scripts/golang-http-linux.sh
pkg/core/proxy/integrations/mysql/recorder/conn.go
pkg/core/proxy/integrations/mysql/replayer/conn.go
pkg/core/proxy/proxy.go
pkg/core/proxy/tls/ca.go
pkg/core/proxy/tls/tls.go
pkg/models/instrument.go
pkg/service/record/record.go
pkg/service/replay/replay.go

testcase req time is used for time freezing, so we used first testcase req time as an alias for the application frozen time, we used this time to calculate the NotBefore and NotAfter field in certificate signing request. The duration of the signed certificate is 2 years. (backdate - 1 yr, backdate + 1 yr) 
Closes: #2662

fix: certificate invalid if application time is before cert issuance time

---

pkg/util.go

-  Replaced returning `nil` for error handling with returning the actual error in case of an issue while opening the directory.
- Added defer `dir.Close()` to ensure the directory is closed after reading its contents.
- Enhanced logging for errors when reading directory contents.
- NA

fix: Improve error handling and resource management in ReadSessionIndices

---

cli/provider/service.go
pkg/models/tele.go
pkg/platform/telemetry/telemetry.go
pkg/service/tools/service.go
pkg/service/tools/tools.go

The current implementation of telemetry map involves creation of a global map of type `map[string]interface{}`, there might be race conditions emerging on accessing the telemetry map at same time on 2 or more places, replacing it with sync.Map prevents race conditions as it inbuilt uses locks 
**Fixes:** #[issue number that will be closed through this PR]
- NA
- NA
- NA

chore: telemetry as sync map to avoid race conditions

---

.github/PULL_REQUEST_TEMPLATE.md
pkg/core/app/app.go
pkg/core/core_linux.go

This pull request introduces changes to improve the lifecycle management of channels and context handling in the `pkg/core/app/app.go` file. The changes include adding proper channel closures, introducing a dedicated context for Docker metadata operations, and ensuring graceful cleanup of resources. These updates aim to enhance the stability and maintainability of the application.
* Added logic to close the `inodeChan` and `containerIPv4` channels in the `extractMeta` and `getDockerMeta` methods to ensure proper cleanup when the context is canceled or operations are complete. (`pkg/core/app/app.go`, [[1]](diffhunk://#diff-a80f8fc1c17c3284b4e1933765194a11f185ee638e77b09def015a984860b564L263-R272) [[2]](diffhunk://#diff-a80f8fc1c17c3284b4e1933765194a11f185ee638e77b09def015a984860b564R356-R35 …

fix: keploy stuck if docker container already in use

---

cli/config.go
utils/utils.go

I add a default case in AskForConfirmation so that any input other than “y”/“yes” or “n”/“no” (including Ctrl+C) is immediately treated as “no” and returns, allowing the program to exit gracefully.
**Closes:** #2766
- NA
- https://github.com/keploy/keploy/issues/2766
- NA
prepare `keploy.yaml` and run the following command.
input `abc`
```sh
$ ./keploy config --generate
▓██▓▄
▓▓▓▓██▓█▓▄
████████▓▒
▀▓▓███▄      ▄▄   ▄               ▌
▄▌▌▓▓████▄    ██ ▓█▀  ▄▌▀▄  ▓▓▌▄   ▓█  ▄▌▓▓▌▄ ▌▌   ▓
▓█████████▌▓▓   ██▓█▄  ▓█▄▓▓ ▐█▌  ██ ▓█  █▌  ██  █▌ █▓
▓▓▓▓▀▀▀▀▓▓▓▓▓▓▌  ██  █▓  ▓▌▄▄ ▐█▓▄▓█▀ █▓█ ▀█▄▄█▀   █▓█
▓▌                           ▐█▌                   █▌
▓
version: 2-dev
Config file already exists. Do you want to override it? [y/n]: abc
$
``` …

fix: bug keploy config --generate gets stuck on invalid input when keploy.yml exists

---

utils/signal_others.go

Issue - #2899
Test execution stops after ~950 test cases. This is because the Keploy is closing the db client connections from the application which in return motivates the application to create more connections with which the no of connections are increasing and exceeding the normal soft limit of file descriptors. This issue of `closing the client connections `is being investigated. Although for big applications with huge mocks and tests normal value of soft limit of file descriptors is less. So we have increased the soft limit of file descriptors in this PR.

fix: increase fd limit of user app

---

pkg/core/core_linux.go
pkg/core/hooks/hooks.go
pkg/core/hooks/kernelComm.go
pkg/service/replay/replay.go
utils/inc.go

This pull request introduces improvements to eBPF hook state management and synchronization, focusing on ensuring reliable hook reloading between test sets and preventing race conditions. The changes add proper locking for shared state, implement a robust hook reload mechanism with retry logic, and update the replay logic to reload hooks between test sets for better isolation and reliability.
**eBPF Hook State Management and Synchronization:**
* Added mutex locking around `appID` updates and accesses in the `Hooks` struct to prevent race conditions when loading, unloading, and interacting with hooks. (`pkg/core/hooks/hooks.go`) [[1]](diffhunk://#diff-30b8a9b622fa625b8a1d1c7e579f0b625e39db86d902577dd71f18605c66bd11R108-R112) [[2]](diffhunk://#diff-30b8a9b622fa625b8a1d1c7e579f0b625e39db86d90 …

feat: reload hooks between testset runs for fresh sessions

---

pkg/core/proxy/mockmanager.go

This pull request introduces a revision tracking mechanism to the `MockManager` in `pkg/core/proxy/mockmanager.go`. The main goal is to maintain a monotonically increasing revision number that updates whenever the in-memory set or sort order of mocks changes. This helps external consumers efficiently detect changes to the mocks without scanning the entire set.
**Revision tracking enhancements:**
* Added a `rev` field to `MockManager` and imported `sync/atomic` for thread-safe revision management. [[1]](diffhunk://#diff-9a133c08bbc468a05091b48c725f0228d5a31aaeeda815c2cbc6383ff33ed855R11) [[2]](diffhunk://#diff-9a133c08bbc468a05091b48c725f0228d5a31aaeeda815c2cbc6383ff33ed855R22-R23)
* Implemented `Revision()` and `bumpRevision()` methods to expose and update the revision number atomically. …

feat: implement revision tracking in MockManager for better state

---

cli/provider/docker.go
cli/provider/util.go

This pull request updates how the Docker run alias is generated in the `getAlias` function to improve compatibility with SSH agent forwarding and Docker BuildKit across Linux, Windows, and macOS environments. The main changes ensure that the SSH agent socket is correctly mounted inside the container and relevant environment variables are set, which helps with workflows that require SSH authentication (e.g., cloning private repositories) and enables Docker BuildKit for better build performance.
**Docker run alias improvements:**
* Added mounting of the SSH agent socket (`SSH_AUTH_SOCK`) and set `SSH_AUTH_SOCK` environment variable in the Docker run command for Linux, Windows, and macOS to support SSH agent forwarding. [[1]](diffhunk://#diff-005a1ac6747afd3dcc1ae728d6f79aa1178af829814bda78e6 …

fix: mount ssh agent to container incase of running keploy with docker

---

pkg/core/proxy/integrations/grpcV2/match.go

This pull request makes a minor adjustment to the fuzzy matching logic for gRPC request bodies in the `FilterMocksBasedOnGrpcRequest` function. The threshold for skipping fuzzy matching due to large body size has been increased.
* The threshold for skipping fuzzy matching was raised from 256KB to 512KB, and the debug log now includes the actual body length for better traceability. (`pkg/core/proxy/integrations/grpcV2/match.go`)

feat: increase grpc request body size limit for fuzzy matching

---

pkg/core/hooks/hooks.go

- Remove using retprobeMaxActive to avoid using tracefs to load kprobes. Loading kprobes with tracefs is leading to a buffer overflow, which is crashing the machine kernel in high-concurrency and load scenarios. 
**Closes:** This kernel panic occurs with high concurrency and load. 
```
/tmp/apport-614/VmCoreDmesg:3156:[ 8661.382348] [T1559791] detected buffer overflow in strcpy
/tmp/apport-614/VmCoreDmesg:3159:[ 8661.382457] [T1559791] invalid opcode: 0000 [#1] PREEMPT SMP NOPTI
/tmp/apport-614/VmCoreDmesg:3162:[ 8661.382665] [T1559791] RIP: 0010:fortify_panic+0x13/0x20
/tmp/apport-614/VmCoreDmesg:3180:[ 8661.384649] [T1559791]  ? fortify_panic+0x13/0x20
/tmp/apport-614/VmCoreDmesg:3182:[ 8661.384804] [T1559791]  ? fortify_panic+0x13/0x20
/tmp/apport-614/VmCoreDmesg:3184:[ 8661.384955] …
```

fix:remove retprobeMaxActive to avoid using tracefs to load kprobes
