.gitignore
Dockerfile
docker-compose.yaml
go.mod
go.sum
http/regression/regression.go
pkg/platform/mgo/mongo.go
server/server.go
web/web.go

build: Embed UI and add docker-compose

---

pkg/match.go
pkg/match_test.go
server/server.go

Made some changes in jsonMatch function in match.go for making comparison between actual and expected Maps to fix bugs and added some comments for better understanding .

fix: made TestJsonDiff function work correctly solving #17

---

.github/workflows/go.yml

The action would run build and test when if:
- A PR is raised against the main branch
- Commits are done to the main branch

build: setup github action to build and test

---

README.md

add link to demo video

---

graph/generated/generated.go
graph/schema.graphqls
graph/schema.resolvers.go

- Fixes #5 
- Added `normalizeTests` mutation to normalize multiple test cases at once

add normalizeTests mutation

---

.github/Pull_request_template.md

Signed-off-by: Unnati <chhabraunnati324@gmail.com>
cc @slayerjain   @nehagup

added file

---

README.md

Closes: #84 
The reference to the Keploy Go samples repository has been updated, an example using Echo/PostgreSQL has been used on the Keploy README.
None 
NA

Update README.md with new samples-go repository

---

.github/workflows/go.yml

Enable `KEPLOY_ENABLE_DEDUP: true` for covering more testcases in keploy build checks
Original           | Updated
:--------------------: |:--------------------:
**original screenshot**  | <b>updated screenshot </b> |

build: update workflow by enabling dedup

---

.github/workflows/go.yml
pkg/platform/mgo/mongo.go

- Go test will fail if overall test run returns false
Original           | Updated
:--------------------: |:--------------------:
**original screenshot**  | <b>updated screenshot </b> |

build: update github action for testing

---

.github/workflows/go.yml
.github/workflows/release.yml

temporarily disable commit message linting

ci: temporarily disable commit message linting

---

.github/ISSUE_TEMPLATE/--documentation-update.yaml
.github/docs.svg
README.md

Update Readme and add docs site reference links
Shortened readme basis on user-interviews and added docs website links
Documentation

[docs]: Update Readme and add docs site reference links

---

docker-compose-debug.yaml
docker-compose-dev.yaml
docker-compose.yaml

Closes: [#102 ](https://github.com/keploy/keploy/issues/102)
Renamed  the `web_1` container to `keploy` 
NA
NA
Original           | Updated
:--------------------: |:--------------------:
**original screenshot**  | <b>updated screenshot </b> |

chore: rename the container in docker-compose

---

README.md

Signed-off-by: Axit Patel <patelakshit2025@gmail.com>
Fixes #113

readme_updated 

---

.github/workflows/docker-publish.yml
Dockerfile

Closes: #118
This PR adds arm64 docker image builds to our CI pipeline.
Here's a sample run on my repo: [ditsuke/keploy/runs/ ...](https://github.com/ditsuke/keploy/runs/6073962531?check_suite_focus=true).
And the docker image build: [docker.io:ditsuke/keploy](https://hub.docker.com/repository/docker/ditsuke/keploy).
None
NA
None

feat(ci): Add support for arm64 docker images

---

.github/workflows/main.yml
goreleaser.yaml

Closes: #117
This PR introduces making releases using GoReleaser. The web UI is fetched from `keploy/ui` and is embedded into the binary while creating a new release.
NA

ci: migrate to goreleaser

---

README.md

Signed-off-by: khanjasir90 <khanmohdjasir@gmail.com>
Closes: #122 

Added Gitpod Badge to Readme.md file

---

README.md

Announcing launch of rewards for keploy contributors on README.md!

docs: Added keploy rewards to README.md

---

.gitignore
graph/utils.go

Closes: #137 
Adds url field in graphQL update testcase query.

Adds url field in input of update testcase graphql

---

.gitignore
graph/utils.go
pkg/models/tc.go
pkg/platform/mgo/tdb.go
pkg/service/regression/regression.go

Closes: #138 
adds update function only updates http request and response of graphql query input testcase

updates http request and response  of graphql query input testcase.

---

go.mod
go.sum
graph/generated/generated.go
graph/model/models_gen.go
graph/schema.graphqls
pkg/service/regression/regression.go
pkg/utils.go
pkg/utils_test.go

#134 
Closes: #134 
Added check in CompareHeader function to ignore noisy header fields

fix: ignores the noisy fields of headers

---

.github/workflows/go.yml

Signed-off-by: Sarthak Shyngle <50234097+Sarthak160@users.noreply.github.com>
- Changes codefish semantic-release-action version to v1

build: add change version for codefish-semantics

---

.github/workflows/docker-publish.yml

Builds failing due to cosign - https://github.com/keploy/keploy/runs/8017473304?check_suite_focus=true   
I've updated cosign to the latest stable version `v1.11.1`

fix(gha):  update cosign to solve signing issues

---

.github/workflows/greetings.yml

Temp fixing the greetings action based on the suggestion provided here - https://github.com/actions/first-interaction/issues/101#issuecomment-1262487501

ci: temp fix the greetings action

---

.github/workflows/release.yml
gon.json
goreleaser.yaml

build: add support for macos notarization

---

.github/workflows/release.yml

ci: fix syntax error in github pipeline

---

.github/workflows/release.yml

ci: decouple release pipeline and set dependencies

---

.github/workflows/release.yml

ci: fix release pipeline git checkout

---

.github/workflows/release.yml
goreleaser.yaml

ci: fix identation in goreleaser.yaml

---

README.md

Fixed Test Example under 'Integration with native Go test framework' section of README.md
- #135
Closes: #135
- The file name was mentioned before the code sample block for easier understanding. 
- Code sample runtime error was fixed that was causing it to not compile.
NA
NA
| **![image](https://user-images.githubusercontent.com/66906402/196054373-d34856df-8c7d-4211-96e0-5d9560b8a83b.png)** | <b>![image](https://user-images.githubusercontent.com/66906402/196054436-54340e56-3bcc-455e-b73f-d128364f2913.png)</b> |

Fix README Test Example

---

.github/FUNDING.yml

Create FUNDING.yml for pizza parties

---

grpc/grpcserver/server.go
http/regression/regression.go

Signed-off-by: re-Tick <jain.ritik.1001@gmail.com>
- EOF always returned false in fetching testcase
Closes: #223
updates the "eof" response header value to true in test-export.

fix: update the eof header to true in test-export

---

pkg/service/regression/regression.go

fix: fix error when body is not json

---

.github/workflows/docker-publish.yml
.github/workflows/main.yml
cmd/server/main.go
goreleaser.yaml
grpc/mock/mock.go
server/server.go

feat: add more information during startup

---

pkg/service/testCase/testCase.go

Signed-off-by: gouravkrosx <gouravgreatkr@gmail.com>
Change log level from error to info when no directory found containing testcases.

refactor: change log level to info in readtcs 

---

pkg/service/regression/regression.go

Signed-off-by: gouravkrosx <gouravgreatkr@gmail.com>
This PR fixes the comparison of headers when there is a multivalue header.
`NA`

fix: make multivalue headers separated by comma delimiter

---

go.mod
go.sum
grpc/grpcserver/server.go
pkg/service/regression/regression.go
pkg/service/testCase/testCase.go
pkg/utils.go

feat: autodetect time as noisy field

---

Dockerfile
go.mod
go.sum
pkg/match.go
pkg/match_test.go
pkg/service/regression/regression.go

fix: detect schema changes for noisy jsons

---

README.md

Signed-off-by: SanskritiHarmukh <sanskritiharmukh1908@gmail.com>
Shifted the SDK support portion in Readme towards the top.
NA

added SDK link towards top of readme

---

graph/tools.go

chore: rename codegen tools to keploy_codegen_tools

---

Dockerfile

ci: fix npm install failure in dockerfile

---

go.mod
go.sum

Signed-off-by: Sarthak Shyngle <50234097+Sarthak160@users.noreply.github.com>

refactor(go-mod): update keploy go-sdk version to latest

---

go.mod
go.sum
server/server.go

Keploy server was throwing an error on the latest go-sdk version because the UrlRegex property had been updated in the go-sdk recently. So I just changed that property in the Keploy server as well and updated the go-sdk version in the go.mod file.
Closes: #278 

Fixed Minor Bug

---

README.md

Signed-off-by: Neha Gupta <gneha21@yahoo.in>

docs: removed caching on badge

---

CONTRIBUTING.md
README.md

Updated Contributing Guide for contributors
NA

Updating Contribution Guide

---

README.md

- Adding details of the only unit test case file needed
Closes: #60
Added the details in the README.md file. Currently, only the code of the file is mentioned. Added details for more clarity such as filename and file location.
`NA`
`NA`
| ![originaldoc](https://user-images.githubusercontent.com/78696767/221963663-48e47cfb-cecb-43b0-929d-03651081e95d.png)              | ![updateddoc](https://user-images.githubusercontent.com/78696767/221963674-7e78aa7c-9503-404b-9b58-e7a39c50cf11.png) |

Adding details of the only unit test case file needed.

---

.github/workflows/telemetry-check.yml

Predefining Installation_id in telemetry-check

Predefining Installation_id in telemetry-check

---

.github/workflows/telemetry-check.yml

-  telemetry-check failing as it doesn't have sudo permissions
Added sudo wherever required

Adding permissions to telemetry-check

---

.github/workflows/telemetry-check.yml

- telemetry-check is failing due to some permission issues .
-  fixed  permission issues of telemetry-check

Correcting telemetry-check github action

---

README.md

Fixed a simple typo in the ReadMe file

fix: typo in ReadMe

---

README.md

- Installation link is broken.
Closes: #435 
Updated the installation link in the README

chore: update installation link in README

---

grpc/grpcserver/server.go
pkg/platform/telemetry/service.go
pkg/platform/telemetry/telemetry.go
pkg/service/regression/regression_test.go
pkg/service/testCase/testCase.go

Previously RecordedTest and RecordedMock events  are triggered at the time of testing so that we get total no of test/mocks generated but this causes a problem to create telemetry charts like giving duplicate events etc . So changed the trigger from test to record . From now these events get trigger per recorded mock or test .

Changed trigger for RecordedTest and RecordedMock events

---

grpc/grpcserver/server.go
pkg/platform/fs/tele.go
pkg/platform/telemetry/service.go
pkg/platform/telemetry/telemetry.go
pkg/service/regression/regression.go
pkg/service/testCase/testCase.go

- Make Telemetry more informative and make keploy-config folder hidden
1. Added mock count and mock type to RecordedTestAndMocks event
2. Added MockTestRun event for test run for mocking feature
3. Added mock type to RecordedMock event
4. Change the folder keploy-config to .keploy-config 

Added more info to telemetry events

---

http/regression/request.go

adds deprecated tag in go-docs in request.go

docs(http/regression): adds deprecated tag in go-docs in request.go

---

README.md

I have updated new method for running keploy in our PC for mac, Linux and Linux ARM architecture inside readme.md
- [ ✓] My code follows the style guidelines of this project.
- [ ✓] I have performed a self-review of my own code.
- [✓ ] I have commented my code, particularly in hard-to-understand areas.
- [ ✓] I have made corresponding changes to the documentation.
- [✓ ] My changes generate no new warnings.
- [ ✓] I have added tests that prove my fix is effective or that my feature works.
- [ ✓] New and existing unit tests pass locally with my changes.

docs: Update new download method updated in README.md

---

cmd/server/main.go
go.mod
go.sum

Problem: The version that is returned in main.go file is random because the list of tags are random and are not sorted. 
Solution: Iterated through the list of tags and returned latest version

fix: return latest version than random version in main.go

---

.github/ISSUE_TEMPLATE/--bug-report.yaml
.github/ISSUE_TEMPLATE/--feature-request.yaml

Fixed Typo in Bug-Report and Feature-Request Templates

---

.github/workflows/release.yml
.gitignore
Dockerfile
web/public/index.html

we are focusing on improving the command line interface (CLI) experience for Keploy with the help of our community. As part of this effort, we have deprecated the user interface (UI) and it will no longer be available
Added a simple index file to display that on the localhost6789. 
Added exclusion for the same file in gitignore
Removed the UI build workflow.

refactor(web): deprecate ui and change workflow for the same

---

.github/workflows/release.yml

fix: remove build ui in workflow

---

.github/workflows/sample-run.yml

Rename telemetry-check workflow to proper name
Renamed telemetry-check workflow

fix: Rename workflow

---

pkg/hooks/launch.go
pkg/hooks/loader.go
pkg/service/test/test.go

-Updating function names and variables for IP address of user.
Updating name for function and variables for IP address in struct and corresponding function 

updating variable and corresponding function name 

---

server/server.go

chore: pkg imported more than once

---

README.md

- Readme file got corrupted.
- Updated README.md file
`NA`

docs: fix corrupted readme

---

.github/workflows/go.yml
.github/workflows/main.yml
.github/workflows/release.yml
.github/workflows/sample-run.yml
README.md

-  Some go modules of `cilium/ebpf` library requires go1.19+ 
- Upgrade go version to **1.20**
`NA`

ci: upgrade go version to 1.20

---

.github/workflows/sample-run.yml
pkg/hooks/launch.go
pkg/service/test/test.go

- Failed to get the docker network in case of test mode.
- Parsed docker network using provided app command.
`NA`

fix: failed to get docker network using app cmd

---

.github/workflows/go-self-hosted.yml
.github/workflows/main-self-hosted.yml
.github/workflows/sample-run-self-hosted.yml

Added a new build to check for arm64 files changes.

features: pipeline to run arm64 build 

---

pkg/proxy/proxy.go

- #662 
Closes: #662 
Used io.MultiReader to enable reading TLS sockets.

fix: use io.MultiReader to read tls sockets

---

pkg/proxy/proxy.go

When Keploy is executed with unsupported dependencies such as Oracle, Keploy encounters issues. This is because certain protocols are not straightforward; instead of the typical one-to-one client request to server response, there might be situations where multiple requests emerge simultaneously from the client. Similarly, the server could issue multiple responses concurrently. Hence, the sequence of requests and responses becomes unpredictable.
Closes: #668 
Implemented two Go routines to capture buffers for both requests and responses. Established two channels: one for the destination and another for the client. Upon capturing a request or response, relay it to the appropriate channel and subsequently write to either the destination or the client.
The case of server sending the first …

fix: add generic flow to unknown protocols

---

.gitignore
cmd/record.go
cmd/test.go

Adds the shorthand flag for the CLI commands

fix: adds the shorthand for the cli cmd flags

---

goreleaser.yaml

ci: fix yaml bug in release pipeline

---

pkg/platform/yaml/model.go
pkg/platform/yaml/utils.go
pkg/service/test/output.go
pkg/service/test/test.go

fix: remove noise assertion during test and fix json diff error

---

pkg/proxy/proxy.go

- #710
Closes: #710
Added Keploy CA. to JVM trusted CA store.

feat: add support for java ca stores

---

cmd/examples.go
cmd/record.go
cmd/root.go
cmd/test.go

- Refactor variable names
Removed logic and renamed variables 
-->

refactor variables renames and conditions updated

---

pkg/clients/clients.go
pkg/clients/docker/docker_client.go
pkg/hooks/launch.go
pkg/hooks/loader.go

Add docker internal client to extract network from container

---

README.md

This reverts commit 6241f77e6a754aa8b0bad86b0e6601fee45ca007.

Revert "docs: remove explicit docker network from readme (#716)"

---

pkg/models/mock.go
pkg/platform/yaml/model.go
pkg/platform/yaml/spec/postgres.go
pkg/proxy/integrations/genericParser/genericParser.go
pkg/proxy/integrations/postgresParser/postgres_parser.go
pkg/proxy/integrations/postgresParser/utils.go
pkg/proxy/proxy.go

- [x ] New feature (non-breaking change which adds functionality)
- [ x] My code follows the style guidelines of this project.
- [x ] I have performed a self-review of my own code.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [ x] I have made corresponding changes to the documentation.
- [ x] My changes generate no new warnings.
- [x ] I have added tests that prove my fix is effective or that my feature works.
- [x ] New and existing unit tests pass locally …

feat: add support for streaming in postgres wire parser

---

pkg/proxy/integrations/httpparser/httpparser.go

- Application panics due to nil pointer exception. In the httpParser package at line 313.
Added a check for the kind of mock before accessing the http request and response.

fix: adds a check for the kind of mock before accessing the fields

---

cmd/record.go
cmd/root.go
cmd/test.go
pkg/hooks/connection/factory.go
pkg/hooks/connection/tracker.go
pkg/hooks/launch.go
pkg/hooks/loader.go
pkg/hooks/ringBufReader.go
pkg/platform/yaml/model.go
pkg/platform/yaml/yaml.go
pkg/proxy/integrations/genericParser/genericParser.go
pkg/proxy/integrations/genericParser/util.go
pkg/proxy/integrations/httpparser/httpparser.go
pkg/proxy/integrations/mongoparser/mongoparser.go
pkg/proxy/integrations/postgresParser/postgres_parser.go
pkg/proxy/integrations/postgresParser/utils.go
pkg/proxy/proxy.go
pkg/proxy/util/util.go
pkg/service/test/match.go
pkg/service/test/test.go
pkg/util.go

-  #743
- Replace some print statements with debug logs.
- Configure zap logger to prepend keploy Emoji

refactor: configure zap logger to prepend keploy Emoji

---

pkg/proxy/integrations/httpparser/httpparser.go

When we capture a testcase with Keploy that uses the expect header, it breaks in the test mode in the decode outgoing function because the function is not able to decode the body of the request.
Closes: #750 
I added support for the expect header in the decodeOutgoingHttp function wherein , if the request contains the expect header, we write the 100-continue response to the user and then append the body in the request and send it back to the decodeOutgoingHttp function.

fix: added support for expect header in the test mode

---

pkg/proxy/integrations/httpparser/httpparser.go

Add debug logs to the handleChunkedRequests and handleChunkedResponses methods in the http parser so that they can be used to debug problems with chunking easily.
Added debug logs in all the functions that are a part of handling the chunked requests and responses in Keploy.

style: added debug logs to the chunking logic

---

cmd/root.go
pkg/proxy/proxy.go

- Adds connection ids and ip addresses in the zap logger as fields to debug the flow in proxy.
Closes: 
Adds the fields in the logger instance to log the values in each log statement of proxy package.

debug: adds connection ip address and id fields in zap

---

README.md

- The goal is to check for the latest keploy docker image and download that during setup.
Closes: #782 
I updated the README.md file here https://github.com/keploy/keploy#-docker-installation- where we are setting alias .
I think it should be
alias keploy='sudo docker run --pull always --name keploy-v2 -p 16789:16789 --network keploy-network --privileged --pid=host -it -v "$(pwd)":/files -v /sys/fs/cgroup:/sys/fs/cgroup -v /sys/kernel/debug:/sys/kernel/debug -v /sys/fs/bpf:/sys/fs/bpf -v /var/run/docker.sock:/var/run/docker.sock --rm ghcr.io/keploy/keploy' 
NA
| **original screenshot** | …

added feature self-update keploy docker image

---

pkg/proxy/proxy.go

fix: set cfssl log level to error

---

pkg/hooks/launch.go
pkg/hooks/loader.go
pkg/hooks/ringBufReader.go
pkg/proxy/integrations/genericParser/genericParser.go
pkg/proxy/integrations/grpcparser/grpc_parser.go
pkg/proxy/integrations/httpparser/httpparser.go
pkg/proxy/integrations/mongoparser/mongoparser.go
pkg/proxy/integrations/postgresParser/postgres_parser.go
pkg/proxy/proxy.go
pkg/proxy/util/util.go
pkg/service/record/record.go
pkg/service/serve/serve.go
pkg/service/test/test.go
pkg/util.go

- CLI process exits but the user app is still running. 
Closes: #786 
Recovers from the panic and gracefully stops the user app and removes the ebpf hooks.

fix: recovers from panic and stops the user app

---

cmd/root.go
cmd/test.go

- Updated the commands for KeployCli
Closes: #801 
Revamped the sample command name and fixed spelling error in Keploy test log!

refactor: commands for keployCLI

---

pkg/proxy/integrations/httpparser/httpparser.go

When the server returns a 503 Slow Down error, Keploy is not able to parse the chunked response body.
Closes: #804 
We use a single reader for reading the whole body to avoid synchronisation errors, also improved the logging.

fix: fixed parsing error in chunked responses

---

pkg/proxy/proxy.go

- Moving from log to logger for getting better logs and gracefully killing the application.
Closes: #807
The loaded hooks aren't stopped well as a result the user application is running in background.
Same as above the user application isn't killed
User application is killed and shutdown in a graceful way

refactor: remove log panic and shift from log to logger

---

pkg/proxy/integrations/mongoparser/mongoparser.go
pkg/proxy/proxy.go

Closes: #813
Implemented threadsafe auto increment for unique and readable connection ids.

fix: make connection ids autoincrement

---

pkg/hooks/connection/tracker.go
pkg/hooks/launch.go
pkg/hooks/loader.go
pkg/hooks/util.go
pkg/proxy/proxy.go

- Earlier keploy required application network beforehand to capture external calls when running in docker env and that is not the ideal user experience. Since user can use docker compose file without mentioning the network and rely on dynamically created network.
Closes: https://github.com/keploy/keploy/issues/600
- I took advantage of the docker events. There was an event listener which listens to the container created type event in the codebase. By inspecting the application container inside this listener provided the network of the application container.
- I dynamically injected this network to the keploy container.
- Refactored proxy.go file to get the proxy port with the help of hooks struct and also refactored launch.go file to improve some logging. 
`NA`
|        Original         | …

feat: add dynamic network injection to keploy container

---

pkg/proxy/integrations/grpcparser/grpc_parser.go

fix: handle eof in grpc parser

---

pkg/proxy/integrations/mongoparser/mongoparser.go
pkg/proxy/proxy.go

- Adds a length check for matching the mongo requests in test to avoid breaking the application 
Closes: #821 
Adds a length check for the mongo requests documents.

fix: adds a check before comparing mongoRequests

---

pkg/proxy/proxy.go

- whenever trying to make an outgoing HTTP call in the node app, it fails during test phase and returns error: ```UNABLE_TO_VERIFY_LEAF_SIGNATURE```
Closes: #822
The node maintains its own set of certificated while making outgoing calls, which weren't present leading to a failed TLS handshake with the client. 
To fix this ca certificates that are stored in Keploy binary are exported and stored as temporary files.
This path to the certificate is then given to the node app via the environment, which then fixes the outgoing HTTP call's verification issue.
Node just needs the path to this ca certificate instead of certificate at any particular location

fix: temp ca for outgoing http calls for node

---

pkg/proxy/proxy.go

- Replacing fatal logs with logger errors. 
Incase of fatal errors, for eg docker run project the tempCertifcatePath generator would have created a fatal error.

refactor: replacing fatal with logger

---

pkg/proxy/proxy.go

fix: ca.crt permissions set to 666

---

go.mod
go.sum
pkg/proxy/integrations/postgresParser/postgres_parser.go
pkg/proxy/integrations/postgresParser/postgres_transcoder.go
pkg/proxy/integrations/postgresParser/utils.go
pkg/proxy/proxy.go

I have used this https://github.com/Shashwat79802/django-postgresql to test my PR

fix: last Mock object was not captured resulting in failing testrun

---

README.md

docs: change messaging on readme and add wsl pre-requisite

---

pkg/hooks/launch.go
pkg/service/test/test.go

Closes: [#900](https://github.com/keploy/keploy/issues/900)
This issue was occurring because keploy in test mode is clashing with closing fucntions. Removed clashing using channels

fix: stop keploy while test

---

pkg/models/const.go
pkg/proxy/integrations/genericParser/genericParser.go
pkg/proxy/integrations/genericParser/util.go

Closes: #950
Checked if the request buffer can be stored as ASCII string and if so stored the same.

feat: readable mocks

---

README.md
cmd/root.go
keploy.sh

- Helps in one touch install keploy.
Closes: #994 
Easily installs keploy on OS
```source keploy.sh```

feat:one touch install

---

README.md

update:download link

---

keploy.sh

update: ending if quotes

---

cmd/mockrecord.go
cmd/mocktest.go
cmd/record.go
cmd/serve.go
cmd/test.go
pkg/proxy/proxy.go
pkg/service/mockrecord/mockrecord.go
pkg/service/mockrecord/service.go
pkg/service/mocktest/mocktest.go
pkg/service/mocktest/service.go
pkg/service/record/record.go
pkg/service/record/service.go
pkg/service/serve/serve.go
pkg/service/serve/service.go
pkg/service/test/service.go
pkg/service/test/test.go

Closes: #1000 
added proxy port as  a flag

added port proxy as a flag

---

READMEes-Es.md

- [X ] New feature (non-breaking change which adds functionality)
- [ X] My changes generate no new warnings.

Adding spanish readme 

---

cmd/root.go

Closes: #997 
customized the EncoderConfig to use `zapcore.CapitalColorLevelEncoder` for `EncodeLevel`
| **original screenshot** | <b>![image](https://github.com/keploy/keploy/assets/91385321/9e4c46a8-c6f4-46e1-aede-d61e497a3b0d) </b> |

feat: logger with different color for each level

---

.github/workflows/docker-publish.yml

Updating cosign since some actions are failing: https://github.com/keploy/keploy/actions/runs/6729993045/job/18295619463#step:3:83

ci: update cosign in docker ci

---

cmd/record.go
cmd/serve.go
pkg/hooks/loader.go
pkg/service/serve/graph/resolver.go
pkg/service/serve/graph/schema.resolvers.go
pkg/service/serve/serve.go
pkg/service/serve/service.go
pkg/service/test/service.go
pkg/service/test/test.go

update:serve with app command

---

keploy.sh
pkg/hooks/loader.go

- Unused flag to be removed and updated to new version

remove: unused flag of one click install

---

pkg/service/test/util.go

An incorrect log was being printed by Keploy which was leading to confusion for the users.
I removed that log from the file and also the variables associated with it

style: removed incorrect log

---

cmd/record.go
keploy-config.yaml
pkg/hooks/connection/factory.go
pkg/hooks/loader.go
pkg/models/config.go
pkg/platform/interface.go
pkg/platform/yaml/yaml.go
pkg/service/mockrecord/mockrecord.go
pkg/service/mocktest/mocktest.go
pkg/service/record/record.go
pkg/service/record/service.go
pkg/service/serve/serve.go
pkg/service/test/test.go

Closes: #1059 
Added filters in keploy-config.yaml by which mock will get recorded but testcases won't generate 
NA
NA
NA

Adding option to configure recording of test cases 

---

pkg/service/serve/graph/resolver.go
pkg/service/serve/graph/schema.resolvers.go

Closes: #1113 
Removed noise logic.

fix: removed noise logic

---

pkg/service/test/test.go

- fix issue which cause fails to replace url host to containerIp on test-mode in case of docker 
- Here is the error stack - 

fix: fail to replace url host to containerIp on test-mode

---

README.md

docs: change flow of readme

---

keploy.sh

Revert "feature: added catalogue for installation method"

---

cmd/record.go
cmd/test.go
pkg/service/test/match.go

Closes: #1161
removed for loop to avoid error

fix: removed for loop to avoid error

---

pkg/models/const.go
pkg/models/http.go
pkg/proxy/integrations/httpparser/httpparser.go

feature: passthrough for telemetry in record and test

---

cmd/examples.go
cmd/root.go

- Removing the dual appearance of Docker commands.
Closes: #1199 

refactor: keploy examples

---

.github/workflows/node-linux.sh

- Adding CI test to check keploy test sets.
Closes: #1219
Checking a custom test set.

add:workflow to test single test sets

---

.github/ISSUE_TEMPLATE/--bug-report.yaml
.github/ISSUE_TEMPLATE/--documentation-update.yaml
.github/ISSUE_TEMPLATE/--feature-request.yaml

Added more repository options in issue template
Closes: #1227 
added repos - [blog-website](https://github.com/keploy/blog-website), [samples-rust](https://github.com/keploy/samples-rust), [samples-python](https://github.com/keploy/samples-python), [samples-csharp](https://github.com/keploy/samples-csharp)
Feature
NA

feat: add repo options in issue template

---

keploy.sh

Updated the one click install script to work with the latest version of keploy

fix: updated docker alias in keploy.sh

---

pkg/hooks/settings/clock.go
pkg/platform/yaml/testReport.go
pkg/platform/yaml/yaml.go

- Solves error concat
Closes: #1170
Fixes string concat.

refactor: concat strings in error logs

---

.gitignore

Ignoring keploy generated test cases via git ignore.

refactor:add keploy generated tests in gitignore

---

pkg/hooks/loader.go
pkg/proxy/integrations/genericParser/genericParser.go
pkg/proxy/integrations/mongoparser/mongoparser.go
pkg/proxy/integrations/mysqlparser/mysqlparser.go
pkg/proxy/integrations/postgresParser/postgres_parser.go

fix: prevent error logging of failed to read from client incase app exits

---

cmd/examples.go
keploy.sh

Closes: #1230 
Updated installation scripts to incorporate Docker functionalities to enable Keploy setup on Darwin.

feat: Docker support for Keploy installation on Darwin

---

cmd/root.go

Closes: #1262
Hiding details of the file and line number of keploy binary while running logs.

feat: hide file details of keploy logger in binary

---

pkg/service/record/record.go
pkg/service/serve/serve.go
pkg/service/test/test.go

fix: fixed typo of word gracefully

---

pkg/proxy/integrations/genericParser/genericParser.go

Closes: #1296 
This is happening because in the parser a slice is not being copied in a particular place and empty slice is being passed. Fixed this.

fix: missing copy of slice

---

go.mod
go.sum
pkg/proxy/integrations/postgresParser/postgres_parser.go
pkg/proxy/integrations/postgresParser/utils.go

refactor: provide some null checks in pg parser

---

pkg/proxy/integrations/mongoparser/mongoparser.go
pkg/proxy/proxy.go
pkg/proxy/util/util.go

1. Update TLS verification
2. Update mongo parser.

fix: mongo read function

---

pkg/service/test/output.go
pkg/service/test/test.go

-#1374
Closes: #1374
Added error logging and handling in the diff viewer library logic. 

fix: handle errors in console diff library

---

pkg/platform/yaml/yaml.go
pkg/proxy/integrations/postgresParser/postgres_parser.go
pkg/proxy/integrations/postgresParser/postgres_transcoder.go
pkg/proxy/integrations/postgresParser/utils.go

feat: make priority based fuzzy match for config mocks

---

pkg/platform/yaml/utils.go

Closes: #1378
Removed regex match for test-set and filtered testReports while filtering test-sets.

fix: generalize test-set name

---

cmd/test.go
pkg/graph/schema.resolvers.go
pkg/models/config.go
pkg/service/generateConfig/generateConfig.go
pkg/service/test/absmatch.go
pkg/service/test/match.go
pkg/service/test/output.go
pkg/service/test/service.go
pkg/service/test/test.go
pkg/service/test/util.go
utils/utils.go

feat:ignore order of data

---

README.md
READMEes-Es.md

Added more relevant badges in addition to the existing ones.

feat: add relevant tags & badges on readme

---

cmd/test.go

fix: updates the permission for the keploy dir while exiting the test

---

pkg/hooks/launch.go

Closes: #1542
Updated the code to use the safer method `IsUserAppTerminateInitiated`
No tests added
NA
None

fix: race condition in userAppShutdownInitiated check

---

pkg/service/test/test.go
pkg/service/test/util.go

- Fixed the fail and success.
Closes: #1555

fix:count of fail,test & total

---

pkg/platform/yaml/testReport.go

- [bug]: Uncontrolled data used in path expression
Closes: #1558 
Incorporating the path validation step before performing file operations.
NA
NA

ValidatedFilePath

---

pkg/service/test/test.go

- Hide complete test summary in case of app not running
Closes: #1577
-If there are testcases then the test summary and coverage opportunity will appear otherwise not.
- I tested it with and without testcases.

[feature]: hide complete test summary in case of app not running

---

pkg/util.go

- Let run the custom names 
Closes: #1601
test-suites can be renamed to custom names and can be executed as well.

refactor:custom names support

---

cmd/test.go
pkg/graph/schema.resolvers.go
pkg/service/test/service.go
pkg/service/test/test.go
pkg/service/test/util.go

Closes: #https://github.com/keploy/keploy/issues/1606
Refactor generate report

refactor: generate report

---

pkg/hooks/loader.go
pkg/proxy/integrations/mongoparser/mongoparser.go

Incase of mongo parser if a config mock is used it is to be updated in `consumedMocks`

refactor:update mocks for used mocks in mongo parser

---

pkg/platform/yaml/mockDb/mockDb.go
pkg/platform/yaml/mockDb/util.go
pkg/platform/yaml/reportDb/reportDb.go
pkg/platform/yaml/testDb/testDb.go
pkg/platform/yaml/testDb/util.go
pkg/platform/yaml/yaml.go

refactor: mock initaliser and filtering

---

pkg/platform/yaml/mockDb/mockDb.go
pkg/platform/yaml/reportDb/reportDb.go
pkg/platform/yaml/testDb/testDb.go
pkg/platform/yaml/utils.go
pkg/platform/yaml/yaml.go

refactor:using yaml defind write in report

---

README.md

docs: correct slack and supported os, add record-replay gif

---

cmd/test.go
pkg/service/test/test.go

feat: add log for test-report url

---

pkg/proxy/integrations/httpparser/httpparser.go
pkg/proxy/integrations/httpparser/match.go
pkg/proxy/proxy.go

-  debug logs are missing in the proxy.go and httpParser.go
Closes: #
Adds the debug logs in proxy

style: adds debug logs in proxy/http-parser

---

.github/workflows/test_workflow_scripts/node-linux.sh
config/config.go
pkg/service/replay/replay.go

1. SelectedTests feature is missed from the refactored code base. Added it.

fix: add selectedTests feat

---

pkg/core/core.go
pkg/core/proxy/integrations/http/decode.go
pkg/core/proxy/integrations/http/http.go
pkg/core/proxy/proxy.go
pkg/models/instrument.go
pkg/service/record/record.go
pkg/service/replay/replay.go

- Sync some commit & sync commit (fix: DNS resolution in fedora)
- Sync commit 

fix: dns resolution in fedora

---

pkg/core/core.go

fix:lint errors

---

pkg/platform/yaml/yaml.go

keploy test and reports were not accessible by all users corrected it 

fix: perm for keploy files

---

.github/workflows/docker-publish.yml

chore: bump cosign version to 3.4.0

---

pkg/core/proxy/integrations/postgres/v1/util.go

- fix panic in pg parser
- Add length check in `mergeMocks` function

fix: add length check in pg parser

---

README.md
pkg/core/proxy/integrations/http/decode.go
pkg/core/proxy/integrations/http/match.go

Fuzzy matching is not working reliably and is not able to match the body even if there is a small difference between them.
Added schema matching in case of a json body type and also added some useful logs that can be used for debugging if matching fails in the future.

fix: added schema match for JSON body

---

cli/provider/cmd.go
config/config.go
config/default.go
pkg/core/proxy/integrations/http/decode.go
pkg/models/instrument.go
pkg/service/replay/replay.go

- Passthrough should be configurable in dedicated parsers
- Made passthrough configurable in the HTTP parser.
`NA`

feat: make passthrough in http parser configurable

---

pkg/util.go

refactor: add keploy test-id header in simulate

---

config/default.go

- Flags present in the config file should be lowercase.
- Made `disableANSI` lowercase in the config file.

chore: made `disableANSI` flag case lowercase

---

utils/utils.go

Parameterise the logic for starting keploy in the docker mode from the binary mode.
Added a variable to be able to set the url of the directory to pull from.

chore: Parameterise binary to docker logic

---

.github/actions/tester/install.sh

- Test pipeline of gin-mongo is failing. 
- Maintain the order while reading the pre-recorded test-sets.
`NA`

fix: test pipeline failing due to test-set order

---

cli/provider/cmd.go
config/config.go
config/default.go
pkg/service/replay/replay.go

feat: add a hook function to extract testReports

---

pkg/service/replay/replay.go

Rest of the tests do not run in case one fails because of timeout
Continuing even in case of timeout issues.

fix: timeout causing issues in test run

---

pkg/core/proxy/integrations/generic/encode.go
pkg/core/proxy/integrations/generic/match.go
pkg/core/proxy/integrations/http/match.go
pkg/core/proxy/integrations/util/util.go

- Redis mocks were not readable.
- Changed the condition of ASCII printable to return true even if it is not printable according to Unicode.
`NA`

refactor: change ascii print condition

---

utils/utils.go

Closes: #https://github.com/keploy/keploy/issues/1908

docker env fix

---

pkg/core/proxy/integrations/postgres/v1/decode.go
pkg/core/proxy/integrations/postgres/v1/match.go

refactor: remove binary matching for postgres sorted mocks 

---

utils/utils.go

- Docker container commands were not there.
- Changed in the docker commands searching patterns
`NA`

feat: add support for docker container commands

---

.github/workflows/release.yml

- Fixed the release function to 1.26.2 (the stable releaser for Alpha-23)
Solves https://github.com/keploy/keploy/issues/1929

fix: releaser version

---

pkg/core/proxy/integrations/postgres/v1/decode.go
pkg/core/proxy/integrations/postgres/v1/encode.go
pkg/core/proxy/integrations/postgres/v1/match.go
pkg/core/proxy/integrations/postgres/v1/util.go

refactor: update redundant logs in pg parser

---

pkg/core/app/app.go
utils/utils.go

- Send kill signal to docker group
- Refactor error logging
Closes: https://github.com/keploy/keploy/issues/1932

fix: send kill to container group

---

utils/utils.go

- fix the lint issue
- Handle error received from the `SendSignal` method to fix the lint issue.
`NA`

chore: fix lint issue

---

goreleaser.yaml

feat: add mac binary release

---

pkg/core/proxy/integrations/generic/match.go
pkg/core/proxy/integrations/http/match.go
pkg/core/proxy/integrations/mongo/match.go
pkg/core/proxy/integrations/mysql/decode.go
pkg/core/proxy/integrations/postgres/v1/match.go
pkg/core/proxy/mockmanager.go
pkg/core/proxy/util.go

Closes: https://github.com/keploy/keploy/issues/1946  https://github.com/keploy/keploy/issues/1901
- added mock kind checks in parsers
- return different mock address for unfiltered and filtered mocks

fix: race in pg and type filtering in parsers

---

keploy.sh

1. Added sudo in installation script
2. remove error msgs of docker from installation script

fix: sudo access in Darwin installation

---

.github/workflows/golang_docker.yml
.github/workflows/golang_linux.yml
.github/workflows/java_linux.yml
.github/workflows/node_docker.yml
.github/workflows/node_linux.yml
.github/workflows/python_docker.yml
.github/workflows/python_linux.yml
.github/workflows/test_workflow_scripts/golang-docker.sh
.github/workflows/test_workflow_scripts/golang-linux.sh
.github/workflows/test_workflow_scripts/java-linux.sh
.github/workflows/test_workflow_scripts/node-docker.sh
.github/workflows/test_workflow_scripts/node-linux.sh
.github/workflows/test_workflow_scripts/python-docker.sh
.github/workflows/test_workflow_scripts/python-linux.sh
.github/workflows/test_workflow_scripts/update-docker.sh
pkg/core/app/app.go
pkg/core/proxy/integrations/grpc/match.go
pkg/core/proxy/integrations/http/match.go
pkg/core/proxy/integrations/integrations.go
pkg/core/proxy/integrations/mongo/decode.go
pkg/core/proxy/integrations/mongo/match.go
pkg/core/proxy/integrations/mysql/decode.go
pkg/core/proxy/integrations/mysql/match.go
pkg/core/proxy/integrations/postgres/v1/match.go
pkg/core/proxy/mockmanager.go

Closes: https://github.com/keploy/keploy/issues/1467

chore: add race in docker and native

---

pkg/service/utgen/README.md

Add windows installation docs for unit test generation documentation

docs: add windows installation

---

README-UnitGen.md
README.md

docs: add unit-gen docs

---

pkg/platform/yaml/configdb/testset/db.go

- Solves https://github.com/keploy/keploy/issues/1969

chore: move error in config read to utils

---

.github/workflows/python_docker.yml

Add missing python-docker workflow.

ci: add python docker workflow

---

pkg/core/proxy/integrations/mysql/comStmtPrepareOk.go
pkg/core/proxy/integrations/mysql/decode.go
pkg/core/proxy/integrations/mysql/encode.go
pkg/core/proxy/integrations/mysql/mysql.go
pkg/core/proxy/integrations/mysql/okPacket.go
pkg/core/proxy/integrations/mysql/operation.go
pkg/core/proxy/integrations/mysql/resultsetPacket.go
pkg/models/mysql.go
utils/log/logger.go

Fixed the datetime parsing issue in mysql, added null check, removed redundant structs in the parser and added support for base64 payloads

fix: Datetime parsing in mysql

---

pkg/models/testcase.go
pkg/platform/yaml/testdb/db.go
pkg/platform/yaml/yaml.go
pkg/service/replay/replay.go
pkg/service/replay/service.go
pkg/service/tools/service.go
pkg/service/tools/tools.go

1. Expose delete testCase or testSet functionality in the test service
2. Add ignore test functionality in the config sevice

feat: expose delete test  in test service

---

cli/provider/cmd.go

1. add config path to all commands
2. remove config unMarshall limitation to specific commands like test and record.

fix: remove config limitation

---

main.go
utils/utils.go

Removes the user docker compose file after usage

fix: remove user docker compose file after use

---

utils/utils.go

Fixed kebab error for nested flags and nested structs in config

fix: kebabCase bug for nested flag

---

pkg/core/proxy/integrations/mysql/authMoreData.go
pkg/core/proxy/integrations/mysql/authSwitchRequestPacket.go
pkg/core/proxy/integrations/mysql/authSwitchResponsePacket.go
pkg/core/proxy/integrations/mysql/comChangeUserPacket.go
pkg/core/proxy/integrations/mysql/comFetchPacket.go
pkg/core/proxy/integrations/mysql/comPingPacket.go
pkg/core/proxy/integrations/mysql/comStmtCloseMoreData.go
pkg/core/proxy/integrations/mysql/comStmtClosePacket.go
pkg/core/proxy/integrations/mysql/comStmtPrepareOk.go
pkg/core/proxy/integrations/mysql/comStmtPreparePacket.go
pkg/core/proxy/integrations/mysql/comStmtResetPacket.go
pkg/core/proxy/integrations/mysql/comStmtSendLongDataPacket.go
pkg/core/proxy/integrations/mysql/encode.go
pkg/core/proxy/integrations/mysql/eofPacket.go
pkg/core/proxy/integrations/mysql/errPacket.go
pkg/core/proxy/integrations/mysql/executePacket.go
pkg/core/proxy/integrations/mysql/handshakeResponseOkPacket.go
pkg/core/proxy/integrations/mysql/handshakeResponsePacket.go
pkg/core/proxy/integrations/mysql/handshakeV10Packet.go
pkg/core/proxy/integrations/mysql/match.go
pkg/core/proxy/integrations/mysql/operation.go
pkg/core/proxy/integrations/mysql/queryPacket.go
pkg/core/proxy/integrations/mysql/resultsetPacket.go
pkg/core/proxy/integrations/mysql/util.go
pkg/models/mysql.go

- MySQL packets type assertion failing
Closes: #2021
- Removed the redundant structs and used the structs from models.
`NA`

fix: mysql packets type assertion

---

pkg/models/config.go

- Fix the spaces of struct.
Closes: https://github.com/keploy/keploy/issues/2035

fix: case of config

---

cli/provider/cmd.go
config/config.go
pkg/service/replay/replay.go

* CoverageCommand isn't needed as it is just overwritten by coverage flag.

fix: fixing coverage command

---

pkg/service/replay/replay.go
pkg/service/replay/service.go
pkg/service/replay/utils.go

refactor: add test coverage data in the AfterTestHook

---

cli/provider/cmd.go
config/config.go
config/default.go
pkg/service/orchestrator/rerecord.go

Closes: #2051 
Added `in-ci` flag which checks if the scripts are being used in CI or not

feat: in CI flag

---

pkg/models/testcase.go
pkg/models/testrun.go
pkg/service/replay/replay.go
pkg/service/replay/utils.go

Added ignored field in the test reports and test run summary.

fix: add ignored field in test run summary

---

pkg/service/replay/utils.go

refactor: fix linter issue in testreport verdict

---

.github/workflows/go_windows.yml
utils/signal_windows.go

There was no windows pipeline so changes that broke the windows release did not get caught.
Add pipeline to build windows binary on every pull request

feat: windows pipeline

---

cli/test.go
pkg/platform/yaml/yaml.go
pkg/service/record/record.go
pkg/service/replay/replay.go
utils/ctx.go

Closes:  https://github.com/keploy/keploy/issues/2008
Added a context cancel check to ensure no error is sent while stopping.

add: handle the closing of yaml file write

---

keploy.sh

- Update keploy.sh to remove keploybin to keploy for AMD

feat : Update keploy.sh to remove keploybin to keploy

---

.github/workflows/ossSync.yml

add: sync pipeline

---

pkg/platform/coverage/javascript/javascript.go

fix: total coverage for node app

---

.github/actions/tester/install.sh
.github/workflows/test_workflow_scripts/golang-docker.sh
.github/workflows/test_workflow_scripts/golang-linux.sh
.github/workflows/test_workflow_scripts/java-linux.sh
.github/workflows/test_workflow_scripts/node-docker.sh
.github/workflows/test_workflow_scripts/node-linux.sh
.github/workflows/test_workflow_scripts/python-docker.sh
.github/workflows/test_workflow_scripts/python-linux.sh
config/default.go

Current implementation of the GitHub actions autogenerate has issues like generating in the root. I'm disabling this until this is fixed.

chore: disable github actions autogen until fixed

---

pkg/util.go

Closes: #2140 
Added a check to consider only directories in the readSession function.
No
NA
NA

fix: fixed `ReadSessionIndices` Function

---

pkg/core/hooks/conn/util.go

- #2154
Closes: #2154
used the url object method directly.

fix: panic in isFiltered when incomming http without port

---

.github/workflows/test_workflow_scripts/python-docker.sh
.github/workflows/test_workflow_scripts/python-linux.sh
cli/config.go
cli/provider/cmd.go
pkg/core/proxy/integrations/postgres/v1/decode.go
pkg/core/proxy/integrations/postgres/v1/encode.go
pkg/core/proxy/integrations/postgres/v1/util.go

fix: failing python native and docker test pipeline

---

pkg/util.go

add a check to override host header if present in the request, currently go client was removing the host header
while making the request.

refactor: override host header if present in the request

---

keploy.sh

- change the overwrite flag before extracting the files to the /tmp directory (-C /tmp).

refactor: move overwrite before changing to /tmp

---

pkg/platform/yaml/configdb/user/db.go

fix: lint error

---

.github/workflows/docker-publish.yml
.github/workflows/release.yml

fix: secret variables mismatch

---

.github/actions/tester/install.sh
pkg/service/replay/absmatch.go

- Added a fix to fail the pipeline if the pilot sends exit status 1
Closes: https://github.com/keploy/keploy/issues/2226

fix: test bench not failing when pilot exits with exit 1

---

cli/provider/docker.go
pkg/service/utgen/ai.go

refactor: set docker image as global variable

---

cli/provider/docker.go
pkg/platform/yaml/configdb/user/db.go

1. installationId was not getting passed env is not getting referred.

fix: docker installationId mismatch

---

pkg/util.go

fix: add a nil pointer check for template

---

pkg/service/utgen/ai.go

refactor: change api server url for utg

---

keploy.sh

macOS ships with an old version of tar which doesn't support --overwrite option so we need to remove the directory first to avoid the "File exists" error

fix: macOS installation failure due to different tar version

---

pkg/platform/auth/auth.go
pkg/service/replay/hooks.go
pkg/service/replay/replay.go

Add and update logs of mock upload.

fix: mock upload logs

---

go.mod
go.sum
pkg/service/utgen/ai.go
pkg/service/utgen/gen.go

Add session token to ensure each run's data is stored correctly.
Closes: https://github.com/keploy/keploy/issues/2265

add: session token for each call

---

keploy.sh

This PR updates the one click install to install without sudo.

update: one click

---

pkg/service/utgen/gen.go
utils/signal_windows.go
utils/utils.go

fix: skip cov calculation for empty test file

---

pkg/core/hooks/kernelComm.go

chore: improve logs

---

pkg/core/hooks/hooks.go

changes : Removing unused parameter which is causing linter issue

fix: linter

---

.github/workflows/test_workflow_scripts/golang-mysql-linux.sh

This PR fixes the random failing of mysql_golang_linux workflow.
Closes: #2286

fix: Fixed mysql_golang_linux workflow

---

pkg/service/replay/hooks.go
pkg/service/replay/replay.go
pkg/service/replay/service.go

- Changed the interface of `AfterTestSetRun` and added a new method to it `AfterTestRun` that will execute once all the test-sets are executed.

refactor: add after test run hook 

---

keploy.sh

Fixed implementation for one click install incase of noRoot flag

fix: oneclick install

---

keploy.sh

* fix: oneclick install
* removed comment
---------

fix: oneclick install (#2304)

---

pkg/service/utgen/ai.go
pkg/service/utgen/gen.go

Provide Context Cancellation for keploy generate
Check if test works before runnning utgen
Closes: #2282 , #2292

fix: context cancellation and check if test works before for keploy utgen

---

pkg/service/utgen/gen.go

Added print statements to show the summary of tests generated
Closes: https://github.com/keploy/keploy/issues/2311

add: summary of utgen

---

README.md

- corrected typos
- corrected fragmentation error :)
- simplified actionable step messages where required
- document now reads without any articulation flaw, as it should be for such a great project
Improves readability, fixes typos and holds the README.md at a higher standard of articulation that it was.
Null
Locally

Typos Fixed: Articulation Improved for Project Outlook

---

cli/provider/service.go
pkg/service/utgen/gen.go

Improved NewUnitTestGenerator function in cli/provider/service.go to take in less parameters
Closes: #2301 
- [] Bug fix (non-breaking change which fixes an issue)

improved NewUnitTestGenerator function

---

READMEja-JP.md

I created Japanese translated README.

docs: add Japanese README

---

pkg/models/ut.go
pkg/service/utgen/assets/test_generation.toml
pkg/service/utgen/gen.go
pkg/service/utgen/prompt.go

Added support of important statements in different languages 
Closes: https://github.com/keploy/keploy/issues/2326

feat: handle import of libraries

---

pkg/service/utgen/gen.go
pkg/service/utgen/prompt.go

Sent absolute path to utg instead of base path
https://github.com/keploy/keploy/issues/2331

chore: absolute file path for test

---

pkg/service/utgen/gen.go

Import the java tests function in correct function with imports

fix: insert test cases and imports in java 

---

pkg/service/utgen/assets/test_generation.toml
pkg/service/utgen/utils.go

Improves prompt for library installation code

Improved prompt for library installation code

---

pkg/service/utgen/ai.go
pkg/service/utgen/gen.go

Have added a support to track the coverage.

chore: tracking coverage after each run

---

.github/workflows/codeql.yml

Integrated - https://github.com/peter-murray/github-security-report-action/issues/5

chore: enable codeql pdf reprot export

---

pkg/core/proxy/integrations/http/match.go

- Corrected logic for HTTP headers matching in HTTP parsers
- Considered all forms of `keploy-test-set-id` and `keploy-test-id`
- `NA`

fix: matching of http headers in http parser

---

cli/provider/cmd.go
config/config.go
pkg/service/utgen/ai.go
pkg/service/utgen/assets/test_generation.toml
pkg/service/utgen/gen.go
pkg/service/utgen/injector.go
pkg/service/utgen/prompt.go
pkg/service/utgen/utils.go

I've updated the import of and requirements of js and ts. 
Also fixed the error message extractor in all languages.
- https://github.com/keploy/keploy/issues/2368

chore: fix error message and imports for js and ts

---

pkg/platform/docker/util.go

fix: docker cancellation bug

---

.github/workflows/golang_docker-compose.yml
.github/workflows/test_workflow_scripts/golang-docker-compose.sh

This PR adds a new pipeline to test go application using docker compose
fixes #2372 

feat: added docker compose pipeline

---

pkg/models/auth.go

chore: add platform in request body 

chore: add platform in request body

---

pkg/service/utgen/ai.go
pkg/service/utgen/gen.go
pkg/service/utgen/injector.go
pkg/service/utgen/prompt.go

https://github.com/keploy/keploy/issues/2398

chore: update call for ut

---

pkg/service/utgen/ai.go

add omit empty for max_completion_tokens

chore: add omit empty for max_completion_tokens

---

pkg/service/utgen/assets/test_generation.toml

https://github.com/keploy/keploy/issues/2405

chore: fix condition in prompts

---

pkg/service/utgen/ai.go
pkg/service/utgen/gen.go

https://github.com/keploy/keploy/issues/2412
Have send request type to utg calls.

chore: send purpose to utg

---

cli/provider/docker.go

- Fixed the logic to pick colima context when the user is using colima.
`NA`
Closes: https://github.com/keploy/keploy/issues/2415

fix: keploy doesn't work on mac colima

---

pkg/agent/proxy/integrations/generic/encode.go
pkg/agent/proxy/integrations/generic/generic.go
pkg/agent/proxy/integrations/grpc/encode.go
pkg/agent/proxy/integrations/grpc/grpc.go
pkg/agent/proxy/integrations/mysql/mysql.go
pkg/agent/proxy/integrations/mysql/recorder/record.go
pkg/agent/proxy/integrations/redis/encode.go
pkg/agent/proxy/integrations/redis/redis.go

Fixes the client close for mysql

fix: client close for mysql

---

.github/ISSUE_TEMPLATE/--bug-report.yaml

fix: update --bug-report.yaml

---

pkg/service/utgen/gen.go

Refactored the logs so that user understand why exactly the utg failed

chore: update log and let user know why test failed

---

cli/provider/core_service_others.go
pkg/service/tools/tools.go

fix: keploy update on macos

---

pkg/service/utgen/ai.go

Added complete params and model to run keploy gen command
https://github.com/keploy/keploy/issues/2423

chore: fix keploy gen case

---

pkg/service/utgen/ai.go
pkg/service/utgen/assets/test_generation.toml
pkg/service/utgen/gen.go
pkg/service/utgen/injector.go
pkg/service/utgen/prompt.go

chore: add import structs and functions

---

pkg/service/utgen/gen.go

This PR introduces error message logging in the discard test cases file.

feat: added error messages in discard test cases file

---

keploy.sh

Adds no root flag to mac os installation script

fix: one click with no root on mac

---

cli/provider/cmd.go
config/config.go
pkg/service/utgen/gen.go

Adds a flaky flag 
1. If test fails, return with no coverage and no more flaky check,
2. If test pass and coverage increases, check flakiness flag, 5 iteration to check flakiness

feat: [UTG] flaky flag and prioritize coverage check over flaky check

---

cli/provider/cmd.go

chore: change expected coverage to 80 percent

---

cli/import.go
cli/provider/cmd.go
cli/provider/service.go
pkg/service/import/import.go
pkg/service/tools/service.go
pkg/service/tools/tools.go

This PR adds feature to import postman collections to keploy tests

feat: Import Postman

---

cli/provider/cmd.go

Correct the incorrect update-template flag

fix: update template flag

---

pkg/models/testrun.go
pkg/platform/coverage/golang/golang.go
pkg/platform/coverage/java/java.go
pkg/platform/coverage/javascript/javascript.go
pkg/platform/coverage/python/python.go

Feature - Add LOC in Coverage struct.

feat: add LOC in coverage reports

---

pkg/service/export/export.go
pkg/service/import/import.go

Previously export postman was not storing response in postman collections.

fix: add responses to postman collections for export functionality

---

.github/workflows/test_workflow_scripts/golang-docker.sh
.github/workflows/test_workflow_scripts/golang-linux.sh
.github/workflows/test_workflow_scripts/golang-mysql-linux.sh
.github/workflows/test_workflow_scripts/java-linux.sh
.github/workflows/test_workflow_scripts/node-docker.sh
.github/workflows/test_workflow_scripts/node-linux.sh
.github/workflows/test_workflow_scripts/python-docker.sh
.github/workflows/test_workflow_scripts/python-linux.sh
pkg/agent/hooks/hooks.go
pkg/agent/proxy/integrations/mysql/wire/phase/query/rowscols/binaryProtocolRowPacket.go
pkg/agent/proxy/integrations/postgres/v1/decode.go
pkg/agent/proxy/proxy.go
pkg/agent/routes/record.go
pkg/agent/routes/testbench.go
pkg/client/app/app.go
pkg/platform/docker/docker.go
pkg/platform/http/agent.go
utils/signal_others.go

- Fixed context cancellation for no mocks
- Changed Info logs to debug logs

fix: newagent for context cancellation

---

.github/workflows/release.yml

ci: fix goreleaser by cleaning the assets

---

.github/workflows/release.yml

Revert "ci: fix goreleaser by cleaning the assets"

---

README.md

This PR adds Keploy Ranking badge in the readme based on - https://trendshift.io/repositories/3262

feat: add ranking badge to readme

---

cli/provider/cmd.go
config/config.go

refactor: rename base-url to base-path

---

pkg/matcher/http/match.go

This pr addds support of global noise. this can be use to ignore the entire body.
I commented out the noise.
```
test:
selectedTests: {}
globalNoise:
global: {
body: {"*": "*"}
}
test-sets: {}
```

feat: support of ignoring entire body as a noise 

---

pkg/matcher/http/match.go

Header matching was causing nil pointer problem in diff in test mode

fix: header matching in test result

---

pkg/models/instrument.go
pkg/service/record/record.go

fix: lint issues

---

.github/workflows/test_workflow_scripts/node-linux.sh
pkg/core/proxy/integrations/http/decode.go
pkg/core/proxy/integrations/http/encode.go
pkg/core/proxy/integrations/http/http.go
pkg/core/proxy/integrations/http/util.go
pkg/core/proxy/integrations/mysql/recorder/conn.go
pkg/core/proxy/proxy.go
pkg/core/proxy/tls/ca.go
pkg/core/proxy/tls/tls.go

- Fixes the race condition due to global variables
- `NA`
Closes: https://github.com/keploy/keploy/issues/2596

fix: race condition in tls connection

---

pkg/core/proxy/integrations/http/match.go
pkg/platform/yaml/mockdb/util.go
pkg/platform/yaml/testdb/util.go

fix: the backward compatibility of http spec

---

go.mod
go.sum

chore: bumpjsondiff to v1.0.5

---

pkg/core/proxy/integrations/redis/redis.go

-  Changed redis parser to generic
Closes: https://github.com/keploy/keploy/issues/2638

fix: make redis as generic

---

README.md

I have fixed the Readme Github icon. 

Readme issue fix

---

.github/ISSUE_TEMPLATE/--bug-report.yaml
.github/PULL_REQUEST_TEMPLATE.md

- Change pr and bug issue template for quick resolutions.
Closes: https://github.com/keploy/keploy/issues/2671

chore: PR and bug templates

---

.github/PULL_REQUEST_TEMPLATE.md
pkg/core/proxy/proxy.go
pkg/core/proxy/util/util.go

- Have added logic to read the buffer till we get all the HTTP Headers.
**Fixes:** #2682 
- NA
- NA
- NA
- NA
**Examples:**
- **Branch Name**: `feature/#1-login-flow`
---

feat: read full http headers to identify other types of requests

---

pkg/core/proxy/integrations/generic/encode.go
pkg/core/proxy/integrations/generic/generic.go
pkg/core/proxy/integrations/grpc/grpc.go
pkg/core/proxy/integrations/grpc/stream.go
pkg/core/proxy/integrations/http/http.go
pkg/core/proxy/integrations/mongo/mongo.go
pkg/core/proxy/integrations/mysql/mysql.go
pkg/core/proxy/integrations/mysql/recorder/record.go
pkg/core/proxy/integrations/postgres/v1/encode.go
pkg/core/proxy/integrations/postgres/v1/postgres.go
pkg/core/proxy/integrations/redis/encode.go
pkg/core/proxy/integrations/redis/redis.go
pkg/core/proxy/proxy.go
pkg/core/proxy/util.go

chore: add connection ID to metadata in mock Spec
change ordering of elements in specific log statements and add connID to metadata
**Fixes:** NA
- NA
- NA
- NA
- NA
**Examples:**
- **Branch Name**: `feat/#1-login-flow`
---

chore: change ordering of log elements and add connID to metadata

---

pkg/models/testcase.go
pkg/platform/yaml/testdb/util.go

Added support for description in test cases
**Fixes:** #123  
- NA 
- NA
- NA
- NA
- NA
**Examples:**
- **Branch Name**: `feat/#1-login-flow`
---

feat: add support for description in testcases

---

pkg/matcher/utils.go

The Current matcher for types other than map had a direct value matching which may cause errors in complex data structures like `[]interface{}`, created a panic
**Fixes:** #123  
- NA
- NA
- NA
- NA
**Examples:**
- **Branch Name**: `feat/#1-login-flow`
---

fix: handle complex data type matching

---

pkg/service/replay/hooks.go
pkg/service/replay/replay.go
pkg/service/replay/service.go

Added a hook point , when consumed mocks is fetched from mockmanager
**Fixes:** #123  
- NA
- NA
- NA
- NA
**Examples:**
- **Branch Name**: `feat/#1-login-flow`
---

chore: add new hooks in replay

---

.github/workflows/test_workflow_scripts/golang-http-linux.sh
pkg/core/proxy/integrations/http/match.go
pkg/core/proxy/integrations/http/util.go
pkg/matcher/http/match.go
pkg/models/http.go
pkg/models/testcase.go
pkg/util.go

Added support for matching non json body by simple comparison
**Fixes:** #2712
- NA
- NA
- NA
- NA
**Examples:**
---

fix: support for matching non json body by simple comparison

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
HACKTOBERFEST_GUIDE.md
README-UnitGen.md
README.md
READMEes-Es.md
READMEja-JP.md

**Updated Slack URLs in the repository to reflect the latest links.**

feat: update slack urls

---

README-UnitGen.md
READMEes-Es.md
READMEja-JP.md

This PR fixes broken links in the READMEja-JP.md, READMEes-ES.md, and README-UnitGen.md files
**Examples:**
---

fix: fixed broken readme links

---

pkg/models/grpc.go
pkg/platform/yaml/mockdb/db.go
pkg/platform/yaml/mockdb/util.go
pkg/platform/yaml/testdb/db.go
pkg/service/export/export.go

This pull request introduces enhancements to error handling and adds support for metadata in gRPC specifications. The most significant changes include adding metadata to the `GrpcSpec` struct, improving error logging for empty or invalid YAML files, and ensuring proper handling of such cases across multiple functions.
* Added a `Metadata` field to the `GrpcSpec` struct in `pkg/models/grpc.go` to support additional metadata for gRPC requests and responses.
* Updated the `EncodeMock` function in `pkg/platform/yaml/mockdb/util.go` to include the new `Metadata` field when encoding gRPC specifications.
* Updated the `decodeMocks` function in `pkg/platform/yaml/mockdb/util.go` to decode the `Metadata` field from gRPC specifications.
* Enhanced error logging in the `GetFilteredMocks` function in …

fix: panic in test db

---

README-UnitGen.md
README.md
READMEes-Es.md
READMEja-JP.md

Updated the GitHub star goal badge across multiple README files to reflect the new milestone target of **20K stars** (previously 10K). 
- NA

fix: update README star goal to 20K

---

cli/config.go
cli/contract.go
cli/export.go
cli/import.go
cli/login.go
cli/mock.go
cli/normalise.go
cli/provider/cmd.go
cli/provider/core_service_linux.go
cli/provider/core_service_others.go
cli/record.go
cli/rerecord.go
cli/templatize.go
cli/test.go
cli/update.go
cli/utgen.go
pkg/service/replay/hooks.go
pkg/service/replay/mock.go
pkg/service/replay/replay.go
pkg/service/replay/service.go

- Add `keploy mock upload` and `keploy mock download` commands for manual communication with mock registry.
- Refactored upload and download mocks functions
**Closes:** https://github.com/keploy/keploy/issues/2751
- NA
- NA
- NA
- NA
**Examples:**
---

feat: add support to upload and download mocks from cloud via cmds

---

pkg/core/proxy/integrations/mysql/wire/phase/query/rowscols/textRowPacket.go

-  improve error message for datetime parsing in DecodeTextRow
- NA
- NA
- NA
- NA
**Examples:**
---

fix: improve error message for datetime parsing in DecodeTextRow

---

pkg/core/proxy/integrations/mysql/recorder/conn.go
pkg/core/proxy/integrations/mysql/replayer/conn.go
pkg/core/proxy/integrations/mysql/replayer/match.go
pkg/core/proxy/integrations/mysql/utils/util.go
pkg/core/proxy/integrations/mysql/wire/decode.go
pkg/core/proxy/integrations/mysql/wire/phase/query/preparedstmt/stmtExecutePacket.go
pkg/core/proxy/integrations/mysql/wire/phase/query/queryPacket.go
pkg/core/proxy/integrations/mysql/wire/phase/query/rowscols/binaryProtocolRowPacket.go
pkg/models/mysql/comm.go
pkg/models/mysql/const.go
pkg/platform/yaml/mockdb/util.go

- Fixed unexpected EOF issue in **COM_STMT_EXECUTE**: The error occurred due to incomplete handling of multiple parameter types—only the string type was processed. Now, all parameter types are correctly supported.
- Enhanced SSL authentication flow for caching_sha2_password: When SSL is enabled, full authentication does not require sending an encrypted password, and no public key exchange is used, and the password can be transmitted in plain text over the secure tunnel. This previously unsupported flow has now been implemented and fixed.
**Closes:** #2805 
- NA
- NA
- NA
- NA
📌 [Branch …

fix: mysql allow unencrypted password when ssl is enabled

---

pkg/core/proxy/integrations/mysql/wire/phase/query/rowscols/textRowPacket.go

- Fix encoding and decoding of MySQL text row packet, no need to handle cases explicitly other than string<enc>.
**Closes:** NA
- NA
- NA
- NA
- NA
**Examples:**
---

fix: mysql text row encode decode

---

pkg/matcher/http/match.go

- 
- NA
- NA
- NA
- NA
**Examples:**
---

chore: increase resilience of status code class assertion

---

pkg/platform/yaml/testdb/util.go

Implemented the loop before assigning the noisy field in the encoded test cases.
**Examples:**
---

fix: noise Updation in test cases

---

pkg/service/replay/hooks.go
pkg/service/replay/replay.go
pkg/service/replay/service.go

This PR adds a new hook called BeforeTestRun to the test execution lifecycle. The hook is designed to be executed before all test sets run, providing an additional extension point for pre-test setup or initialization.
- NA
- NA
- NA
- NA
**Examples:**
- **Branch Name**: `feat/#1-login-flow` (You may skip mentioning the issue number in the branch name if the change is small and the PR …

feat: add new hook before test run

---

pkg/core/proxy/integrations/mysql/replayer/match.go

- Change Error log to Warn log while fetching query signature
- NA
- NA
- NA
- NA
**Examples:**
---

fix: change error to warn while fetching query signature

---

pkg/platform/coverage/python/utils.go

*   **Read Before Write:** The system now checks for an existing `.coveragerc` file before generating a new one.
*   **Intelligent Merging:**
*   If a `.coveragerc` file is found, its contents are parsed.
*   User-defined settings (like custom `omit` paths) are preserved.
*   Keploy's required settings (e.g., `concurrency`, `parallel`, `data_file`) are enforced by either overriding existing values or adding them if they are missing in the `[run]` section.
*   **Fallback Behavior:** If no `.coveragerc` file exists, the original behavior of creating a default configuration is maintained.
- NA
- NA
- NA
- NA
Please ensure your PR title and branch name follow the Keploy …

feat: Preserve user configuration in .coveragerc

---

.gitignore
cli/provider/cmd.go
config/config.go
pkg/service/report/json_diff.go
pkg/service/report/json_diff_fuzz_test.go
pkg/service/report/json_diff_test.go
pkg/service/report/report.go
pkg/service/report/report_test.go

This PR introduces a new feature to the report command that allows users to generate reports from external files and displays only the changed differences in response bodies instead of showing the complete expected and actual content.
- Adds support for loading reports from absolute file paths via a new --report-path flag
- Implements a compact table-style diff view for JSON response bodies that highlights only the changed fields
- Introduces a --body flag to toggle between the new compact diff view and the original full body comparison
```
go test -v -race -cover -bench=. ./pkg/service/report
go test -fuzz=FuzzGenerateTableDiff -fuzztime=2m ./pkg/service/report
go test -fuzz=FuzzParseJSONLoose -fuzztime=2m ./pkg/service/report
go test -fuzz=FuzzFlattenToMap -fuzztime=2m …
```

feat: only show changed diffs of response body in report command

---

.github/workflows/test_workflow_scripts/node-encoding.sh

This pull request improves the process for starting and stopping the `request.js` script within the `.github/workflows/test_workflow_scripts/node-encoding.sh` workflow. The main focus is on more robust handling of the `request.js` process, ensuring it is properly terminated and its process group is managed for reliability.
Process management improvements:
* Added logging to indicate when the Node process is started and its PID is captured, with a check to ensure the PID is valid and the script exits if not.
* Changed the termination logic to stop the entire process group of `request.js` using `kill -TERM` and, if necessary, forcefully kill it with `kill -KILL` after waiting up to 5 seconds for a graceful exit.
- NA (if very …

fix: node encoding pipeline hanging

---

cli/provider/docker.go
pkg/platform/docker/docker.go
pkg/platform/docker/service.go

- 
- NA
- NA
- NA
- NA
**Examples:**
---

fix: create volumes

---

.github/workflows/fuzzer_linux.yml
cli/provider/cmd.go
config/config.go
config/default.go
go.mod
go.sum
pkg/matcher/grpc/match.go
pkg/matcher/grpc/match_test.go
pkg/matcher/utils.go
pkg/platform/yaml/testdb/db.go
pkg/platform/yaml/testdb/db_test.go
pkg/service/replay/grpc.go
pkg/service/replay/grpc_test.go
pkg/service/replay/replay.go
utils/utils.go

- 
**Closes:** https://github.com/keploy/keploy/issues/2990
- NA
- NA
- NA
- NA
**Examples:**
---

feat: add support for json comparison of grpc response

---

.github/CODEOWNERS

- Add second code owner @Sarthak160.
- NA
- NA
- NA
- NA
**Examples:**
---

chore: add second code owner

---

pkg/agent/proxy/integrations/http/decode.go
pkg/agent/proxy/integrations/http/match.go

- 
- NA
- NA
- NA
- NA
**Examples:**
---

Merge main

---

pkg/core/proxy/integrations/http/decode.go
pkg/core/proxy/integrations/http/match.go
pkg/util.go

This PR fixes mock matching in HTTP requests by improving header comparison logic. The changes focus on properly handling multi-value headers and filtering out Keploy-specific headers during comparison.
- Enhanced header comparison with a new utility function for multi-value headers
- Improved header key matching by ignoring Keploy-specific headers with a prefix check
- Added debug logging to help troubleshoot header matching issues
- NA
- NA
- NA
- NA
📌 [Branch Semantics …

fix: mock matching in http 

---

.github/workflows/test_workflow_scripts/node/express_mongoose/node-linux.sh

Signed-off-by: Sarthak160 <rocksarthak45@gmail.com>
This pull request makes the CI script for Node + Mongo + Keploy more robust and fail-fast, aligning it more closely with the reference implementation. The changes ensure that errors are caught and reported clearly, and the pipeline fails immediately on critical issues. It also improves validation of test artifacts and replay results.
**Test artifact and replay validation:**
- After each recording iteration, the script now checks that at least one test or mock file was produced, failing the pipeline if none are found.
- During replay, the script validates that test-set report files exist and that all have a `PASSED` status, failing otherwise. It also checks for data races and errors in replay logs.
These changes make the CI pipeline more …

ci: fix the false succeeding node linux pipeline

---

.github/workflows/test_workflow_scripts/python/flask-secret/python-linux.sh
pkg/util.go

This PR fixes template error handling in the SimulateHTTP function by replacing Go's text/template package with a custom template rendering solution that better handles Keploy-specific placeholders while avoiding conflicts with LaTeX/HTML-like syntax.
- Replaces text/template with custom `utils.RenderTemplatesInString` function
- Improves error handling to be recoverable rather than fatal for template rendering errors
- Removes duplicate template data assignment and streamlines template processing logic
**Closes:** #3090 
- NA
- NA
- NA
- NA
📌 [Branch Semantics …

fix: template error

---

go.mod
go.sum

- Removes integrations from go.mod file
- NA
- NA
- NA
- NA
**Examples:**
---

fix: remove integrations from go.mod
